// Code generated by protoc-gen-go.
// source: vasto.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	vasto.proto

It has these top-level messages:
	BalanceRequest
	StoreMessage
	ClientMessage
	Topology
	FixedCluster
	StoreResource
	Location
	StoreHeartbeat
	ClientHeartbeat
	Empty
	Requests
	Responses
	Request
	PutRequest
	PutResponse
	DeleteRequest
	DeleteResponse
	GetRequest
	GetResponse
	RangeGetRequest
	RangeGetResponse
	Response
	KeyValue
	CopyDoneMessge
	ListRequest
	ListResponse
	ResizeRequest
	ResizeProgress
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// ////////////////////////////////////////////////
// 1. master received request to balance the data
type BalanceRequest struct {
	DataCenter string `protobuf:"bytes,1,opt,name=data_center,json=dataCenter" json:"data_center,omitempty"`
	StoreGroup string `protobuf:"bytes,2,opt,name=store_group,json=storeGroup" json:"store_group,omitempty"`
	StoreCount uint32 `protobuf:"varint,3,opt,name=store_count,json=storeCount" json:"store_count,omitempty"`
}

func (m *BalanceRequest) Reset()                    { *m = BalanceRequest{} }
func (m *BalanceRequest) String() string            { return proto.CompactTextString(m) }
func (*BalanceRequest) ProtoMessage()               {}
func (*BalanceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *BalanceRequest) GetDataCenter() string {
	if m != nil {
		return m.DataCenter
	}
	return ""
}

func (m *BalanceRequest) GetStoreGroup() string {
	if m != nil {
		return m.StoreGroup
	}
	return ""
}

func (m *BalanceRequest) GetStoreCount() uint32 {
	if m != nil {
		return m.StoreCount
	}
	return 0
}

type StoreMessage struct {
}

func (m *StoreMessage) Reset()                    { *m = StoreMessage{} }
func (m *StoreMessage) String() string            { return proto.CompactTextString(m) }
func (*StoreMessage) ProtoMessage()               {}
func (*StoreMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type ClientMessage struct {
	Cluster *Cluster                           `protobuf:"bytes,1,opt,name=cluster" json:"cluster,omitempty"`
	Updates *ClientMessage_StoreResourceUpdate `protobuf:"bytes,2,opt,name=updates" json:"updates,omitempty"`
	Resize  *ClientMessage_Resize              `protobuf:"bytes,3,opt,name=resize" json:"resize,omitempty"`
}

func (m *ClientMessage) Reset()                    { *m = ClientMessage{} }
func (m *ClientMessage) String() string            { return proto.CompactTextString(m) }
func (*ClientMessage) ProtoMessage()               {}
func (*ClientMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ClientMessage) GetCluster() *Cluster {
	if m != nil {
		return m.Cluster
	}
	return nil
}

func (m *ClientMessage) GetUpdates() *ClientMessage_StoreResourceUpdate {
	if m != nil {
		return m.Updates
	}
	return nil
}

func (m *ClientMessage) GetResize() *ClientMessage_Resize {
	if m != nil {
		return m.Resize
	}
	return nil
}

type ClientMessage_StoreResourceUpdate struct {
	Stores   []*StoreResource `protobuf:"bytes,1,rep,name=stores" json:"stores,omitempty"`
	IsDelete bool             `protobuf:"varint,2,opt,name=is_delete,json=isDelete" json:"is_delete,omitempty"`
}

func (m *ClientMessage_StoreResourceUpdate) Reset()         { *m = ClientMessage_StoreResourceUpdate{} }
func (m *ClientMessage_StoreResourceUpdate) String() string { return proto.CompactTextString(m) }
func (*ClientMessage_StoreResourceUpdate) ProtoMessage()    {}
func (*ClientMessage_StoreResourceUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{2, 0}
}

func (m *ClientMessage_StoreResourceUpdate) GetStores() []*StoreResource {
	if m != nil {
		return m.Stores
	}
	return nil
}

func (m *ClientMessage_StoreResourceUpdate) GetIsDelete() bool {
	if m != nil {
		return m.IsDelete
	}
	return false
}

type ClientMessage_Resize struct {
	CurrentClusterSize uint32 `protobuf:"varint,1,opt,name=current_cluster_size,json=currentClusterSize" json:"current_cluster_size,omitempty"`
	NextClusterSize    uint32 `protobuf:"varint,2,opt,name=next_cluster_size,json=nextClusterSize" json:"next_cluster_size,omitempty"`
}

func (m *ClientMessage_Resize) Reset()                    { *m = ClientMessage_Resize{} }
func (m *ClientMessage_Resize) String() string            { return proto.CompactTextString(m) }
func (*ClientMessage_Resize) ProtoMessage()               {}
func (*ClientMessage_Resize) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 1} }

func (m *ClientMessage_Resize) GetCurrentClusterSize() uint32 {
	if m != nil {
		return m.CurrentClusterSize
	}
	return 0
}

func (m *ClientMessage_Resize) GetNextClusterSize() uint32 {
	if m != nil {
		return m.NextClusterSize
	}
	return 0
}

type Topology struct {
	DataCenterClusters map[string]*Cluster `protobuf:"bytes,1,rep,name=data_center_clusters,json=dataCenterClusters" json:"data_center_clusters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Topology) Reset()                    { *m = Topology{} }
func (m *Topology) String() string            { return proto.CompactTextString(m) }
func (*Topology) ProtoMessage()               {}
func (*Topology) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Topology) GetDataCenterClusters() map[string]*Cluster {
	if m != nil {
		return m.DataCenterClusters
	}
	return nil
}

type Cluster struct {
	DataCenter         string           `protobuf:"bytes,1,opt,name=data_center,json=dataCenter" json:"data_center,omitempty"`
	Stores             []*StoreResource `protobuf:"bytes,2,rep,name=stores" json:"stores,omitempty"`
	CurrentClusterSize uint32           `protobuf:"varint,3,opt,name=current_cluster_size,json=currentClusterSize" json:"current_cluster_size,omitempty"`
	NextClusterSize    uint32           `protobuf:"varint,4,opt,name=next_cluster_size,json=nextClusterSize" json:"next_cluster_size,omitempty"`
}

func (m *Cluster) Reset()                    { *m = Cluster{} }
func (m *Cluster) String() string            { return proto.CompactTextString(m) }
func (*Cluster) ProtoMessage()               {}
func (*Cluster) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Cluster) GetDataCenter() string {
	if m != nil {
		return m.DataCenter
	}
	return ""
}

func (m *Cluster) GetStores() []*StoreResource {
	if m != nil {
		return m.Stores
	}
	return nil
}

func (m *Cluster) GetCurrentClusterSize() uint32 {
	if m != nil {
		return m.CurrentClusterSize
	}
	return 0
}

func (m *Cluster) GetNextClusterSize() uint32 {
	if m != nil {
		return m.NextClusterSize
	}
	return 0
}

type StoreResource struct {
	Id      int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Network string `protobuf:"bytes,2,opt,name=network" json:"network,omitempty"`
	Address string `protobuf:"bytes,3,opt,name=address" json:"address,omitempty"`
}

func (m *StoreResource) Reset()                    { *m = StoreResource{} }
func (m *StoreResource) String() string            { return proto.CompactTextString(m) }
func (*StoreResource) ProtoMessage()               {}
func (*StoreResource) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *StoreResource) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *StoreResource) GetNetwork() string {
	if m != nil {
		return m.Network
	}
	return ""
}

func (m *StoreResource) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type Location struct {
	DataCenter string `protobuf:"bytes,1,opt,name=data_center,json=dataCenter" json:"data_center,omitempty"`
	Network    string `protobuf:"bytes,2,opt,name=network" json:"network,omitempty"`
	Address    string `protobuf:"bytes,3,opt,name=address" json:"address,omitempty"`
}

func (m *Location) Reset()                    { *m = Location{} }
func (m *Location) String() string            { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()               {}
func (*Location) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Location) GetDataCenter() string {
	if m != nil {
		return m.DataCenter
	}
	return ""
}

func (m *Location) GetNetwork() string {
	if m != nil {
		return m.Network
	}
	return ""
}

func (m *Location) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

// ////////////////////////////////////////////////
type StoreHeartbeat struct {
	DataCenter string         `protobuf:"bytes,1,opt,name=data_center,json=dataCenter" json:"data_center,omitempty"`
	Store      *StoreResource `protobuf:"bytes,2,opt,name=store" json:"store,omitempty"`
}

func (m *StoreHeartbeat) Reset()                    { *m = StoreHeartbeat{} }
func (m *StoreHeartbeat) String() string            { return proto.CompactTextString(m) }
func (*StoreHeartbeat) ProtoMessage()               {}
func (*StoreHeartbeat) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *StoreHeartbeat) GetDataCenter() string {
	if m != nil {
		return m.DataCenter
	}
	return ""
}

func (m *StoreHeartbeat) GetStore() *StoreResource {
	if m != nil {
		return m.Store
	}
	return nil
}

type ClientHeartbeat struct {
	Location *Location `protobuf:"bytes,1,opt,name=location" json:"location,omitempty"`
}

func (m *ClientHeartbeat) Reset()                    { *m = ClientHeartbeat{} }
func (m *ClientHeartbeat) String() string            { return proto.CompactTextString(m) }
func (*ClientHeartbeat) ProtoMessage()               {}
func (*ClientHeartbeat) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *ClientHeartbeat) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

// ////////////////////////////////////////////////
// // data queries
// ////////////////////////////////////////////////
type Requests struct {
	Requests []*Request `protobuf:"bytes,1,rep,name=requests" json:"requests,omitempty"`
}

func (m *Requests) Reset()                    { *m = Requests{} }
func (m *Requests) String() string            { return proto.CompactTextString(m) }
func (*Requests) ProtoMessage()               {}
func (*Requests) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *Requests) GetRequests() []*Request {
	if m != nil {
		return m.Requests
	}
	return nil
}

type Responses struct {
	Responses []*Response `protobuf:"bytes,1,rep,name=responses" json:"responses,omitempty"`
}

func (m *Responses) Reset()                    { *m = Responses{} }
func (m *Responses) String() string            { return proto.CompactTextString(m) }
func (*Responses) ProtoMessage()               {}
func (*Responses) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *Responses) GetResponses() []*Response {
	if m != nil {
		return m.Responses
	}
	return nil
}

type Request struct {
	Put      *PutRequest      `protobuf:"bytes,1,opt,name=put" json:"put,omitempty"`
	Get      *GetRequest      `protobuf:"bytes,2,opt,name=get" json:"get,omitempty"`
	RangeGet *RangeGetRequest `protobuf:"bytes,3,opt,name=range_get,json=rangeGet" json:"range_get,omitempty"`
	Delete   *DeleteRequest   `protobuf:"bytes,4,opt,name=delete" json:"delete,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *Request) GetPut() *PutRequest {
	if m != nil {
		return m.Put
	}
	return nil
}

func (m *Request) GetGet() *GetRequest {
	if m != nil {
		return m.Get
	}
	return nil
}

func (m *Request) GetRangeGet() *RangeGetRequest {
	if m != nil {
		return m.RangeGet
	}
	return nil
}

func (m *Request) GetDelete() *DeleteRequest {
	if m != nil {
		return m.Delete
	}
	return nil
}

type PutRequest struct {
	KeyValue    *KeyValue `protobuf:"bytes,1,opt,name=key_value,json=keyValue" json:"key_value,omitempty"`
	TimestampNs int64     `protobuf:"varint,2,opt,name=timestamp_ns,json=timestampNs" json:"timestamp_ns,omitempty"`
	TtlMs       uint32    `protobuf:"varint,3,opt,name=ttl_ms,json=ttlMs" json:"ttl_ms,omitempty"`
}

func (m *PutRequest) Reset()                    { *m = PutRequest{} }
func (m *PutRequest) String() string            { return proto.CompactTextString(m) }
func (*PutRequest) ProtoMessage()               {}
func (*PutRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *PutRequest) GetKeyValue() *KeyValue {
	if m != nil {
		return m.KeyValue
	}
	return nil
}

func (m *PutRequest) GetTimestampNs() int64 {
	if m != nil {
		return m.TimestampNs
	}
	return 0
}

func (m *PutRequest) GetTtlMs() uint32 {
	if m != nil {
		return m.TtlMs
	}
	return 0
}

type PutResponse struct {
	Ok     bool   `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
	Status string `protobuf:"bytes,2,opt,name=status" json:"status,omitempty"`
}

func (m *PutResponse) Reset()                    { *m = PutResponse{} }
func (m *PutResponse) String() string            { return proto.CompactTextString(m) }
func (*PutResponse) ProtoMessage()               {}
func (*PutResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *PutResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *PutResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type DeleteRequest struct {
	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (m *DeleteRequest) Reset()                    { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()               {}
func (*DeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *DeleteRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type DeleteResponse struct {
	Ok     bool   `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
	Status string `protobuf:"bytes,2,opt,name=status" json:"status,omitempty"`
}

func (m *DeleteResponse) Reset()                    { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()               {}
func (*DeleteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *DeleteResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *DeleteResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type GetRequest struct {
	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (m *GetRequest) Reset()                    { *m = GetRequest{} }
func (m *GetRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()               {}
func (*GetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *GetRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type GetResponse struct {
	Ok       bool      `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
	Status   string    `protobuf:"bytes,2,opt,name=status" json:"status,omitempty"`
	KeyValue *KeyValue `protobuf:"bytes,3,opt,name=key_value,json=keyValue" json:"key_value,omitempty"`
}

func (m *GetResponse) Reset()                    { *m = GetResponse{} }
func (m *GetResponse) String() string            { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()               {}
func (*GetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *GetResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *GetResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *GetResponse) GetKeyValue() *KeyValue {
	if m != nil {
		return m.KeyValue
	}
	return nil
}

type RangeGetRequest struct {
	Prefix   []byte `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	StartKey []byte `protobuf:"bytes,2,opt,name=start_key,json=startKey,proto3" json:"start_key,omitempty"`
	Limit    uint32 `protobuf:"varint,3,opt,name=limit" json:"limit,omitempty"`
}

func (m *RangeGetRequest) Reset()                    { *m = RangeGetRequest{} }
func (m *RangeGetRequest) String() string            { return proto.CompactTextString(m) }
func (*RangeGetRequest) ProtoMessage()               {}
func (*RangeGetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *RangeGetRequest) GetPrefix() []byte {
	if m != nil {
		return m.Prefix
	}
	return nil
}

func (m *RangeGetRequest) GetStartKey() []byte {
	if m != nil {
		return m.StartKey
	}
	return nil
}

func (m *RangeGetRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type RangeGetResponse struct {
	KeyValues []*KeyValue `protobuf:"bytes,1,rep,name=key_values,json=keyValues" json:"key_values,omitempty"`
}

func (m *RangeGetResponse) Reset()                    { *m = RangeGetResponse{} }
func (m *RangeGetResponse) String() string            { return proto.CompactTextString(m) }
func (*RangeGetResponse) ProtoMessage()               {}
func (*RangeGetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *RangeGetResponse) GetKeyValues() []*KeyValue {
	if m != nil {
		return m.KeyValues
	}
	return nil
}

type Response struct {
	Put      *PutResponse      `protobuf:"bytes,1,opt,name=put" json:"put,omitempty"`
	Get      *GetResponse      `protobuf:"bytes,2,opt,name=get" json:"get,omitempty"`
	RangeGet *RangeGetResponse `protobuf:"bytes,3,opt,name=range_get,json=rangeGet" json:"range_get,omitempty"`
	Delete   *DeleteResponse   `protobuf:"bytes,4,opt,name=delete" json:"delete,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *Response) GetPut() *PutResponse {
	if m != nil {
		return m.Put
	}
	return nil
}

func (m *Response) GetGet() *GetResponse {
	if m != nil {
		return m.Get
	}
	return nil
}

func (m *Response) GetRangeGet() *RangeGetResponse {
	if m != nil {
		return m.RangeGet
	}
	return nil
}

func (m *Response) GetDelete() *DeleteResponse {
	if m != nil {
		return m.Delete
	}
	return nil
}

type KeyValue struct {
	Key   []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *KeyValue) Reset()                    { *m = KeyValue{} }
func (m *KeyValue) String() string            { return proto.CompactTextString(m) }
func (*KeyValue) ProtoMessage()               {}
func (*KeyValue) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *KeyValue) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *KeyValue) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

// ////////////////////////////////////////////////
// // data copying
// ////////////////////////////////////////////////
type CopyDoneMessge struct {
	Shard           int32 `protobuf:"varint,1,opt,name=shard" json:"shard,omitempty"`
	CopyStartTimeNs int64 `protobuf:"varint,2,opt,name=copy_start_time_ns,json=copyStartTimeNs" json:"copy_start_time_ns,omitempty"`
}

func (m *CopyDoneMessge) Reset()                    { *m = CopyDoneMessge{} }
func (m *CopyDoneMessge) String() string            { return proto.CompactTextString(m) }
func (*CopyDoneMessge) ProtoMessage()               {}
func (*CopyDoneMessge) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *CopyDoneMessge) GetShard() int32 {
	if m != nil {
		return m.Shard
	}
	return 0
}

func (m *CopyDoneMessge) GetCopyStartTimeNs() int64 {
	if m != nil {
		return m.CopyStartTimeNs
	}
	return 0
}

// ////////////////////////////////////////////////
// // admin
// ////////////////////////////////////////////////
type ListRequest struct {
	DataCenter string `protobuf:"bytes,1,opt,name=data_center,json=dataCenter" json:"data_center,omitempty"`
}

func (m *ListRequest) Reset()                    { *m = ListRequest{} }
func (m *ListRequest) String() string            { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()               {}
func (*ListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *ListRequest) GetDataCenter() string {
	if m != nil {
		return m.DataCenter
	}
	return ""
}

type ListResponse struct {
	Cluster     *Cluster `protobuf:"bytes,1,opt,name=cluster" json:"cluster,omitempty"`
	ClientCount uint32   `protobuf:"varint,2,opt,name=client_count,json=clientCount" json:"client_count,omitempty"`
}

func (m *ListResponse) Reset()                    { *m = ListResponse{} }
func (m *ListResponse) String() string            { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()               {}
func (*ListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *ListResponse) GetCluster() *Cluster {
	if m != nil {
		return m.Cluster
	}
	return nil
}

func (m *ListResponse) GetClientCount() uint32 {
	if m != nil {
		return m.ClientCount
	}
	return 0
}

type ResizeRequest struct {
	DataCenter  string `protobuf:"bytes,1,opt,name=data_center,json=dataCenter" json:"data_center,omitempty"`
	ClusterSize uint32 `protobuf:"varint,2,opt,name=cluster_size,json=clusterSize" json:"cluster_size,omitempty"`
}

func (m *ResizeRequest) Reset()                    { *m = ResizeRequest{} }
func (m *ResizeRequest) String() string            { return proto.CompactTextString(m) }
func (*ResizeRequest) ProtoMessage()               {}
func (*ResizeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *ResizeRequest) GetDataCenter() string {
	if m != nil {
		return m.DataCenter
	}
	return ""
}

func (m *ResizeRequest) GetClusterSize() uint32 {
	if m != nil {
		return m.ClusterSize
	}
	return 0
}

type ResizeProgress struct {
	Error                     string `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	Progress                  string `protobuf:"bytes,2,opt,name=progress" json:"progress,omitempty"`
	HasNotifiedClientsToStart bool   `protobuf:"varint,3,opt,name=hasNotifiedClientsToStart" json:"hasNotifiedClientsToStart,omitempty"`
	HasNotifiedStoresToStart  bool   `protobuf:"varint,4,opt,name=hasNotifiedStoresToStart" json:"hasNotifiedStoresToStart,omitempty"`
	AreStoresSplit            bool   `protobuf:"varint,5,opt,name=areStoresSplit" json:"areStoresSplit,omitempty"`
	AreStoresReplicated       bool   `protobuf:"varint,6,opt,name=areStoresReplicated" json:"areStoresReplicated,omitempty"`
	AreStoresCaughtUp         bool   `protobuf:"varint,7,opt,name=areStoresCaughtUp" json:"areStoresCaughtUp,omitempty"`
	HasNotifiedClientsToStop  bool   `protobuf:"varint,8,opt,name=hasNotifiedClientsToStop" json:"hasNotifiedClientsToStop,omitempty"`
	HasNotifiedStoresToStop   bool   `protobuf:"varint,9,opt,name=hasNotifiedStoresToStop" json:"hasNotifiedStoresToStop,omitempty"`
}

func (m *ResizeProgress) Reset()                    { *m = ResizeProgress{} }
func (m *ResizeProgress) String() string            { return proto.CompactTextString(m) }
func (*ResizeProgress) ProtoMessage()               {}
func (*ResizeProgress) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *ResizeProgress) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *ResizeProgress) GetProgress() string {
	if m != nil {
		return m.Progress
	}
	return ""
}

func (m *ResizeProgress) GetHasNotifiedClientsToStart() bool {
	if m != nil {
		return m.HasNotifiedClientsToStart
	}
	return false
}

func (m *ResizeProgress) GetHasNotifiedStoresToStart() bool {
	if m != nil {
		return m.HasNotifiedStoresToStart
	}
	return false
}

func (m *ResizeProgress) GetAreStoresSplit() bool {
	if m != nil {
		return m.AreStoresSplit
	}
	return false
}

func (m *ResizeProgress) GetAreStoresReplicated() bool {
	if m != nil {
		return m.AreStoresReplicated
	}
	return false
}

func (m *ResizeProgress) GetAreStoresCaughtUp() bool {
	if m != nil {
		return m.AreStoresCaughtUp
	}
	return false
}

func (m *ResizeProgress) GetHasNotifiedClientsToStop() bool {
	if m != nil {
		return m.HasNotifiedClientsToStop
	}
	return false
}

func (m *ResizeProgress) GetHasNotifiedStoresToStop() bool {
	if m != nil {
		return m.HasNotifiedStoresToStop
	}
	return false
}

func init() {
	proto.RegisterType((*BalanceRequest)(nil), "pb.BalanceRequest")
	proto.RegisterType((*StoreMessage)(nil), "pb.StoreMessage")
	proto.RegisterType((*ClientMessage)(nil), "pb.ClientMessage")
	proto.RegisterType((*ClientMessage_StoreResourceUpdate)(nil), "pb.ClientMessage.StoreResourceUpdate")
	proto.RegisterType((*ClientMessage_Resize)(nil), "pb.ClientMessage.Resize")
	proto.RegisterType((*Topology)(nil), "pb.Topology")
	proto.RegisterType((*Cluster)(nil), "pb.FixedCluster")
	proto.RegisterType((*StoreResource)(nil), "pb.StoreResource")
	proto.RegisterType((*Location)(nil), "pb.Location")
	proto.RegisterType((*StoreHeartbeat)(nil), "pb.StoreHeartbeat")
	proto.RegisterType((*ClientHeartbeat)(nil), "pb.ClientHeartbeat")
	proto.RegisterType((*Empty)(nil), "pb.Empty")
	proto.RegisterType((*Requests)(nil), "pb.Requests")
	proto.RegisterType((*Responses)(nil), "pb.Responses")
	proto.RegisterType((*Request)(nil), "pb.Request")
	proto.RegisterType((*PutRequest)(nil), "pb.PutRequest")
	proto.RegisterType((*PutResponse)(nil), "pb.PutResponse")
	proto.RegisterType((*DeleteRequest)(nil), "pb.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "pb.DeleteResponse")
	proto.RegisterType((*GetRequest)(nil), "pb.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "pb.GetResponse")
	proto.RegisterType((*RangeGetRequest)(nil), "pb.RangeGetRequest")
	proto.RegisterType((*RangeGetResponse)(nil), "pb.RangeGetResponse")
	proto.RegisterType((*Response)(nil), "pb.Response")
	proto.RegisterType((*KeyValue)(nil), "pb.KeyValue")
	proto.RegisterType((*CopyDoneMessge)(nil), "pb.CopyDoneMessge")
	proto.RegisterType((*ListRequest)(nil), "pb.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "pb.ListResponse")
	proto.RegisterType((*ResizeRequest)(nil), "pb.ResizeRequest")
	proto.RegisterType((*ResizeProgress)(nil), "pb.ResizeProgress")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for VastoMaster service

type VastoMasterClient interface {
	RegisterStore(ctx context.Context, opts ...grpc.CallOption) (VastoMaster_RegisterStoreClient, error)
	RegisterClient(ctx context.Context, opts ...grpc.CallOption) (VastoMaster_RegisterClientClient, error)
	ListStores(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	ResizeCluster(ctx context.Context, in *ResizeRequest, opts ...grpc.CallOption) (VastoMaster_ResizeClusterClient, error)
}

type vastoMasterClient struct {
	cc *grpc.ClientConn
}

func NewVastoMasterClient(cc *grpc.ClientConn) VastoMasterClient {
	return &vastoMasterClient{cc}
}

func (c *vastoMasterClient) RegisterStore(ctx context.Context, opts ...grpc.CallOption) (VastoMaster_RegisterStoreClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_VastoMaster_serviceDesc.Streams[0], c.cc, "/pb.VastoMaster/RegisterStore", opts...)
	if err != nil {
		return nil, err
	}
	x := &vastoMasterRegisterStoreClient{stream}
	return x, nil
}

type VastoMaster_RegisterStoreClient interface {
	Send(*StoreHeartbeat) error
	Recv() (*StoreMessage, error)
	grpc.ClientStream
}

type vastoMasterRegisterStoreClient struct {
	grpc.ClientStream
}

func (x *vastoMasterRegisterStoreClient) Send(m *StoreHeartbeat) error {
	return x.ClientStream.SendMsg(m)
}

func (x *vastoMasterRegisterStoreClient) Recv() (*StoreMessage, error) {
	m := new(StoreMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *vastoMasterClient) RegisterClient(ctx context.Context, opts ...grpc.CallOption) (VastoMaster_RegisterClientClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_VastoMaster_serviceDesc.Streams[1], c.cc, "/pb.VastoMaster/RegisterClient", opts...)
	if err != nil {
		return nil, err
	}
	x := &vastoMasterRegisterClientClient{stream}
	return x, nil
}

type VastoMaster_RegisterClientClient interface {
	Send(*ClientHeartbeat) error
	Recv() (*ClientMessage, error)
	grpc.ClientStream
}

type vastoMasterRegisterClientClient struct {
	grpc.ClientStream
}

func (x *vastoMasterRegisterClientClient) Send(m *ClientHeartbeat) error {
	return x.ClientStream.SendMsg(m)
}

func (x *vastoMasterRegisterClientClient) Recv() (*ClientMessage, error) {
	m := new(ClientMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *vastoMasterClient) ListStores(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := grpc.Invoke(ctx, "/pb.VastoMaster/ListStores", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vastoMasterClient) ResizeCluster(ctx context.Context, in *ResizeRequest, opts ...grpc.CallOption) (VastoMaster_ResizeClusterClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_VastoMaster_serviceDesc.Streams[2], c.cc, "/pb.VastoMaster/ResizeCluster", opts...)
	if err != nil {
		return nil, err
	}
	x := &vastoMasterResizeClusterClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type VastoMaster_ResizeClusterClient interface {
	Recv() (*ResizeProgress, error)
	grpc.ClientStream
}

type vastoMasterResizeClusterClient struct {
	grpc.ClientStream
}

func (x *vastoMasterResizeClusterClient) Recv() (*ResizeProgress, error) {
	m := new(ResizeProgress)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for VastoMaster service

type VastoMasterServer interface {
	RegisterStore(VastoMaster_RegisterStoreServer) error
	RegisterClient(VastoMaster_RegisterClientServer) error
	ListStores(context.Context, *ListRequest) (*ListResponse, error)
	ResizeCluster(*ResizeRequest, VastoMaster_ResizeClusterServer) error
}

func RegisterVastoMasterServer(s *grpc.Server, srv VastoMasterServer) {
	s.RegisterService(&_VastoMaster_serviceDesc, srv)
}

func _VastoMaster_RegisterStore_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(VastoMasterServer).RegisterStore(&vastoMasterRegisterStoreServer{stream})
}

type VastoMaster_RegisterStoreServer interface {
	Send(*StoreMessage) error
	Recv() (*StoreHeartbeat, error)
	grpc.ServerStream
}

type vastoMasterRegisterStoreServer struct {
	grpc.ServerStream
}

func (x *vastoMasterRegisterStoreServer) Send(m *StoreMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *vastoMasterRegisterStoreServer) Recv() (*StoreHeartbeat, error) {
	m := new(StoreHeartbeat)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _VastoMaster_RegisterClient_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(VastoMasterServer).RegisterClient(&vastoMasterRegisterClientServer{stream})
}

type VastoMaster_RegisterClientServer interface {
	Send(*ClientMessage) error
	Recv() (*ClientHeartbeat, error)
	grpc.ServerStream
}

type vastoMasterRegisterClientServer struct {
	grpc.ServerStream
}

func (x *vastoMasterRegisterClientServer) Send(m *ClientMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *vastoMasterRegisterClientServer) Recv() (*ClientHeartbeat, error) {
	m := new(ClientHeartbeat)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _VastoMaster_ListStores_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VastoMasterServer).ListStores(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.VastoMaster/ListStores",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VastoMasterServer).ListStores(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VastoMaster_ResizeCluster_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ResizeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VastoMasterServer).ResizeCluster(m, &vastoMasterResizeClusterServer{stream})
}

type VastoMaster_ResizeClusterServer interface {
	Send(*ResizeProgress) error
	grpc.ServerStream
}

type vastoMasterResizeClusterServer struct {
	grpc.ServerStream
}

func (x *vastoMasterResizeClusterServer) Send(m *ResizeProgress) error {
	return x.ServerStream.SendMsg(m)
}

var _VastoMaster_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.VastoMaster",
	HandlerType: (*VastoMasterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListStores",
			Handler:    _VastoMaster_ListStores_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RegisterStore",
			Handler:       _VastoMaster_RegisterStore_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "RegisterClient",
			Handler:       _VastoMaster_RegisterClient_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "ResizeCluster",
			Handler:       _VastoMaster_ResizeCluster_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "vasto.proto",
}

// Client API for VastoStore service

type VastoStoreClient interface {
	Copy(ctx context.Context, opts ...grpc.CallOption) (VastoStore_CopyClient, error)
	CopyDone(ctx context.Context, in *CopyDoneMessge, opts ...grpc.CallOption) (*Empty, error)
}

type vastoStoreClient struct {
	cc *grpc.ClientConn
}

func NewVastoStoreClient(cc *grpc.ClientConn) VastoStoreClient {
	return &vastoStoreClient{cc}
}

func (c *vastoStoreClient) Copy(ctx context.Context, opts ...grpc.CallOption) (VastoStore_CopyClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_VastoStore_serviceDesc.Streams[0], c.cc, "/pb.VastoStore/Copy", opts...)
	if err != nil {
		return nil, err
	}
	x := &vastoStoreCopyClient{stream}
	return x, nil
}

type VastoStore_CopyClient interface {
	Send(*KeyValue) error
	CloseAndRecv() (*Empty, error)
	grpc.ClientStream
}

type vastoStoreCopyClient struct {
	grpc.ClientStream
}

func (x *vastoStoreCopyClient) Send(m *KeyValue) error {
	return x.ClientStream.SendMsg(m)
}

func (x *vastoStoreCopyClient) CloseAndRecv() (*Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *vastoStoreClient) CopyDone(ctx context.Context, in *CopyDoneMessge, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/pb.VastoStore/CopyDone", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for VastoStore service

type VastoStoreServer interface {
	Copy(VastoStore_CopyServer) error
	CopyDone(context.Context, *CopyDoneMessge) (*Empty, error)
}

func RegisterVastoStoreServer(s *grpc.Server, srv VastoStoreServer) {
	s.RegisterService(&_VastoStore_serviceDesc, srv)
}

func _VastoStore_Copy_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(VastoStoreServer).Copy(&vastoStoreCopyServer{stream})
}

type VastoStore_CopyServer interface {
	SendAndClose(*Empty) error
	Recv() (*KeyValue, error)
	grpc.ServerStream
}

type vastoStoreCopyServer struct {
	grpc.ServerStream
}

func (x *vastoStoreCopyServer) SendAndClose(m *Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *vastoStoreCopyServer) Recv() (*KeyValue, error) {
	m := new(KeyValue)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _VastoStore_CopyDone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CopyDoneMessge)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VastoStoreServer).CopyDone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.VastoStore/CopyDone",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VastoStoreServer).CopyDone(ctx, req.(*CopyDoneMessge))
	}
	return interceptor(ctx, in, info, handler)
}

var _VastoStore_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.VastoStore",
	HandlerType: (*VastoStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CopyDone",
			Handler:    _VastoStore_CopyDone_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Copy",
			Handler:       _VastoStore_Copy_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "vasto.proto",
}

// Client API for VastoReader service

type VastoReaderClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
}

type vastoReaderClient struct {
	cc *grpc.ClientConn
}

func NewVastoReaderClient(cc *grpc.ClientConn) VastoReaderClient {
	return &vastoReaderClient{cc}
}

func (c *vastoReaderClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := grpc.Invoke(ctx, "/pb.VastoReader/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for VastoReader service

type VastoReaderServer interface {
	Get(context.Context, *GetRequest) (*GetResponse, error)
}

func RegisterVastoReaderServer(s *grpc.Server, srv VastoReaderServer) {
	s.RegisterService(&_VastoReader_serviceDesc, srv)
}

func _VastoReader_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VastoReaderServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.VastoReader/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VastoReaderServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _VastoReader_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.VastoReader",
	HandlerType: (*VastoReaderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _VastoReader_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vasto.proto",
}

// Client API for VastoWriter service

type VastoWriterClient interface {
	Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error)
}

type vastoWriterClient struct {
	cc *grpc.ClientConn
}

func NewVastoWriterClient(cc *grpc.ClientConn) VastoWriterClient {
	return &vastoWriterClient{cc}
}

func (c *vastoWriterClient) Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error) {
	out := new(PutResponse)
	err := grpc.Invoke(ctx, "/pb.VastoWriter/Put", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for VastoWriter service

type VastoWriterServer interface {
	Put(context.Context, *PutRequest) (*PutResponse, error)
}

func RegisterVastoWriterServer(s *grpc.Server, srv VastoWriterServer) {
	s.RegisterService(&_VastoWriter_serviceDesc, srv)
}

func _VastoWriter_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VastoWriterServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.VastoWriter/Put",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VastoWriterServer).Put(ctx, req.(*PutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _VastoWriter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.VastoWriter",
	HandlerType: (*VastoWriterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Put",
			Handler:    _VastoWriter_Put_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vasto.proto",
}

func init() { proto.RegisterFile("vasto.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1311 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x57, 0xdd, 0x6f, 0x1b, 0x45,
	0x10, 0xcf, 0xd9, 0x71, 0x7c, 0x9e, 0x73, 0x9c, 0x66, 0x13, 0xe8, 0x61, 0x24, 0x48, 0x16, 0x4a,
	0xdd, 0x16, 0x45, 0xa9, 0x2b, 0xd4, 0xaa, 0x45, 0x54, 0xc2, 0xad, 0x8a, 0xd4, 0x0f, 0x55, 0xe7,
	0xb6, 0x20, 0x04, 0x1c, 0x17, 0x7b, 0xeb, 0x9e, 0x7c, 0xbe, 0xbd, 0xee, 0xee, 0x95, 0x9a, 0x3f,
	0x89, 0x17, 0x1e, 0x90, 0x78, 0xe0, 0xaf, 0xe2, 0x95, 0x37, 0xb4, 0x5f, 0x77, 0xe7, 0x8f, 0xd0,
	0x84, 0x37, 0xef, 0xcc, 0x6f, 0xf6, 0x66, 0x66, 0x7f, 0xf3, 0x61, 0xf0, 0xde, 0x44, 0x5c, 0xd0,
	0xa3, 0x8c, 0x51, 0x41, 0x51, 0x2d, 0x3b, 0xc1, 0x1c, 0x3a, 0x5f, 0x47, 0x49, 0x94, 0x8e, 0x48,
	0x40, 0x5e, 0xe7, 0x84, 0x0b, 0xf4, 0x31, 0x78, 0xe3, 0x48, 0x44, 0xe1, 0x88, 0xa4, 0x82, 0x30,
	0xdf, 0x39, 0x70, 0x7a, 0xad, 0x00, 0xa4, 0x68, 0xa0, 0x24, 0x12, 0xc0, 0x05, 0x65, 0x24, 0x9c,
	0x30, 0x9a, 0x67, 0x7e, 0x4d, 0x03, 0x94, 0xe8, 0x81, 0x94, 0x94, 0x80, 0x11, 0xcd, 0x53, 0xe1,
	0xd7, 0x0f, 0x9c, 0xde, 0xb6, 0x01, 0x0c, 0xa4, 0x04, 0x77, 0xa0, 0x3d, 0x94, 0xa7, 0xc7, 0x84,
	0xf3, 0x68, 0x42, 0xf0, 0xdf, 0x35, 0xd8, 0x1e, 0x24, 0x31, 0x49, 0x85, 0x91, 0xa0, 0x4b, 0xd0,
	0x1c, 0x25, 0x39, 0xb7, 0x0e, 0x78, 0x7d, 0xef, 0x28, 0x3b, 0x39, 0x1a, 0x68, 0x51, 0x60, 0x75,
	0xe8, 0x2e, 0x34, 0xf3, 0x6c, 0x1c, 0x09, 0xc2, 0x95, 0x1b, 0x5e, 0xff, 0x92, 0x86, 0x55, 0xae,
	0x3a, 0x52, 0x5f, 0x0a, 0x08, 0xa7, 0x39, 0x1b, 0x91, 0xe7, 0x0a, 0x1d, 0x58, 0x2b, 0x74, 0x0c,
	0x5b, 0x8c, 0xf0, 0xf8, 0x57, 0xa2, 0xbc, 0xf4, 0xfa, 0xfe, 0xaa, 0x7d, 0xa0, 0xf4, 0x81, 0xc1,
	0x75, 0x7f, 0x84, 0xbd, 0x35, 0x37, 0xa2, 0x2b, 0xb0, 0xa5, 0x02, 0xe4, 0xbe, 0x73, 0x50, 0xef,
	0x79, 0xfd, 0x5d, 0x79, 0xd1, 0x02, 0x30, 0x30, 0x00, 0xf4, 0x21, 0xb4, 0x62, 0x1e, 0x8e, 0x49,
	0x42, 0x04, 0x51, 0x6e, 0xbb, 0x81, 0x1b, 0xf3, 0x7b, 0xea, 0xdc, 0x7d, 0x09, 0x5b, 0xfa, 0x83,
	0xe8, 0x18, 0xf6, 0x47, 0x39, 0x63, 0x24, 0x15, 0xa1, 0x09, 0x37, 0x54, 0x8e, 0x3a, 0x2a, 0x9d,
	0xc8, 0xe8, 0x4c, 0x4a, 0x86, 0xd2, 0xe2, 0x2a, 0xec, 0xa6, 0xe4, 0xed, 0x12, 0xbc, 0xa6, 0xe0,
	0x3b, 0x52, 0x51, 0xc1, 0xe2, 0x3f, 0x1d, 0x70, 0x9f, 0xd1, 0x8c, 0x26, 0x74, 0x32, 0x47, 0x2f,
	0x60, 0xbf, 0xf2, 0xe4, 0xd6, 0xde, 0x86, 0xf2, 0xa9, 0x0c, 0xc5, 0x62, 0x8f, 0xee, 0x15, 0x44,
	0x30, 0xd7, 0xf1, 0xfb, 0xa9, 0x60, 0xf3, 0x00, 0x8d, 0x57, 0x14, 0xdd, 0x00, 0x2e, 0x9e, 0x02,
	0x47, 0x17, 0xa0, 0x3e, 0x25, 0x73, 0xc3, 0x2e, 0xf9, 0x13, 0x1d, 0x42, 0xe3, 0x4d, 0x94, 0xe4,
	0xc4, 0xbc, 0xe4, 0xc2, 0x83, 0x6b, 0xcd, 0xed, 0xda, 0x2d, 0x07, 0xff, 0xe1, 0x40, 0xd3, 0x88,
	0xdf, 0x4d, 0xd5, 0xf2, 0x55, 0x6a, 0xef, 0x7a, 0x95, 0xd3, 0xd2, 0x5d, 0x3f, 0x5f, 0xba, 0x37,
	0xd7, 0xa7, 0x7b, 0x08, 0xdb, 0x0b, 0x9f, 0x45, 0x1d, 0xa8, 0xc5, 0x63, 0xe5, 0x71, 0x23, 0xa8,
	0xc5, 0x63, 0xe4, 0x43, 0x33, 0x25, 0xe2, 0x17, 0xca, 0xa6, 0xa6, 0xa0, 0xec, 0x51, 0x6a, 0xa2,
	0xf1, 0x98, 0x11, 0xce, 0x95, 0x2f, 0xad, 0xc0, 0x1e, 0x71, 0x08, 0xee, 0x23, 0x3a, 0x8a, 0x44,
	0x4c, 0xd3, 0x77, 0xa7, 0xe2, 0xff, 0x7c, 0xe0, 0x7b, 0xe8, 0x28, 0xaf, 0xbf, 0x21, 0x11, 0x13,
	0x27, 0x24, 0x3a, 0x43, 0x73, 0xb8, 0x0c, 0x0d, 0x95, 0x50, 0xf3, 0x8a, 0x6b, 0x12, 0xae, 0xf5,
	0xf8, 0x0e, 0xec, 0xe8, 0x3a, 0x2b, 0x2f, 0xef, 0x81, 0x9b, 0x98, 0x78, 0x4c, 0xd5, 0xb7, 0xa5,
	0xb9, 0x8d, 0x31, 0x28, 0xb4, 0xb8, 0x09, 0x8d, 0xfb, 0xb3, 0x4c, 0xcc, 0xf1, 0x0d, 0x70, 0x4d,
	0xdf, 0xe2, 0xe8, 0x32, 0xb8, 0xcc, 0xfc, 0x36, 0xcc, 0x55, 0x1c, 0x32, 0xfa, 0xa0, 0x50, 0xe2,
	0x9b, 0xd0, 0x0a, 0x08, 0xcf, 0x68, 0xca, 0x09, 0x47, 0x57, 0xa1, 0xc5, 0xec, 0xc1, 0x98, 0xb5,
	0xb5, 0x99, 0x16, 0x06, 0xa5, 0x1a, 0xff, 0xe6, 0x40, 0xd3, 0xb6, 0xc9, 0x03, 0xa8, 0x67, 0xb9,
	0x30, 0x7e, 0x76, 0xa4, 0xc5, 0xd3, 0x5c, 0xd8, 0x6f, 0x49, 0x95, 0x44, 0x4c, 0x88, 0x30, 0x89,
	0x50, 0x88, 0x07, 0xa4, 0x44, 0x4c, 0x88, 0x40, 0xc7, 0xd0, 0x62, 0x51, 0x3a, 0x21, 0xa1, 0xc4,
	0xe9, 0x06, 0xb4, 0xa7, 0xbe, 0x2d, 0x85, 0x15, 0xb0, 0xcb, 0x8c, 0x40, 0x12, 0xda, 0x34, 0x8e,
	0xcd, 0x32, 0xbf, 0xba, 0x75, 0x58, 0xb0, 0x01, 0xe0, 0xd7, 0x00, 0xa5, 0x47, 0xe8, 0x0a, 0xb4,
	0xa6, 0x64, 0x1e, 0xea, 0x0a, 0xab, 0x24, 0xf7, 0x21, 0x99, 0xbf, 0x90, 0xb2, 0xc0, 0x9d, 0x9a,
	0x5f, 0xe8, 0x10, 0xda, 0x22, 0x9e, 0x11, 0x2e, 0xa2, 0x59, 0x16, 0xa6, 0xba, 0xb3, 0xd6, 0x03,
	0xaf, 0x90, 0x3d, 0xe1, 0xe8, 0x3d, 0xd8, 0x12, 0x22, 0x09, 0x67, 0xdc, 0x94, 0x47, 0x43, 0x88,
	0xe4, 0x31, 0xc7, 0x5f, 0x80, 0xa7, 0x3e, 0xa9, 0xf3, 0x25, 0x39, 0x4e, 0xa7, 0xea, 0x63, 0x6e,
	0x50, 0xa3, 0x53, 0xf4, 0xbe, 0xac, 0xc6, 0x48, 0xe4, 0xdc, 0x30, 0xd0, 0x9c, 0xf0, 0x21, 0x6c,
	0x2f, 0x84, 0x50, 0x6d, 0x0e, 0x6d, 0xd5, 0x1c, 0xf0, 0x2d, 0xe8, 0x58, 0xc8, 0x39, 0x2f, 0xff,
	0x08, 0xa0, 0xcc, 0xe4, 0x9a, 0x9b, 0x7f, 0x06, 0x4f, 0xe9, 0xcf, 0x77, 0xed, 0x62, 0x3e, 0xeb,
	0xff, 0x95, 0x4f, 0xfc, 0x03, 0xec, 0x2c, 0x3d, 0xa8, 0xbc, 0x35, 0x63, 0xe4, 0x65, 0xfc, 0xd6,
	0x78, 0x62, 0x4e, 0x72, 0x34, 0x70, 0x11, 0x31, 0x11, 0x4a, 0x27, 0x6b, 0x4a, 0xe5, 0x2a, 0xc1,
	0x43, 0x32, 0x47, 0xfb, 0xd0, 0x48, 0xe2, 0x59, 0x6c, 0x07, 0xaa, 0x3e, 0xe0, 0xbb, 0x70, 0xa1,
	0xbc, 0xdd, 0x04, 0x71, 0x0d, 0xa0, 0x70, 0x6e, 0x81, 0xd4, 0x85, 0x77, 0x2d, 0xeb, 0x1d, 0xc7,
	0xbf, 0x3b, 0xb2, 0x86, 0x8c, 0xe5, 0x61, 0x95, 0xd5, 0x3b, 0x05, 0xab, 0x4d, 0x29, 0x28, 0x5a,
	0x1f, 0x56, 0x69, 0xbd, 0x53, 0xd0, 0xda, 0x42, 0x24, 0xaf, 0xaf, 0xaf, 0xf2, 0x7a, 0x7f, 0x91,
	0xd7, 0x06, 0x5d, 0x12, 0xfb, 0xea, 0x12, 0xb1, 0x51, 0x95, 0xd8, 0x06, 0x6d, 0x99, 0xdd, 0x07,
	0xd7, 0x06, 0xb2, 0xfa, 0xa0, 0x32, 0x4d, 0xe5, 0x1c, 0x69, 0x9b, 0xd1, 0x81, 0x87, 0xd0, 0x19,
	0xd0, 0x6c, 0x7e, 0x8f, 0xa6, 0x6a, 0xeb, 0x98, 0x10, 0x89, 0xe3, 0xaf, 0x22, 0x66, 0x9b, 0xb0,
	0x3e, 0xa0, 0x6b, 0x80, 0x46, 0x34, 0x9b, 0x87, 0xfa, 0x19, 0x24, 0xe7, 0xcb, 0x12, 0xd8, 0x91,
	0x9a, 0xa1, 0x54, 0x3c, 0x8b, 0x67, 0xe4, 0x09, 0xc7, 0x47, 0xe0, 0x3d, 0x8a, 0xb9, 0x38, 0xeb,
	0xe6, 0x84, 0xbf, 0x83, 0xb6, 0xc6, 0x9b, 0x6c, 0x9f, 0x71, 0xcb, 0x39, 0x84, 0xf6, 0x48, 0xb5,
	0x4a, 0xb3, 0x50, 0xe9, 0x91, 0xee, 0x69, 0x99, 0xde, 0xa8, 0x86, 0xb0, 0x6d, 0xf6, 0x94, 0xb3,
	0x6e, 0x71, 0xea, 0xd2, 0x95, 0x3d, 0xc1, 0x1b, 0x55, 0x86, 0xd6, 0x5f, 0x75, 0xe8, 0xe8, 0x5b,
	0x9f, 0x32, 0x3a, 0x91, 0x13, 0x41, 0x26, 0x8d, 0x30, 0x46, 0xed, 0x85, 0xfa, 0x80, 0xba, 0xe0,
	0x66, 0x06, 0x61, 0xca, 0xa4, 0x38, 0xa3, 0x2f, 0xe1, 0x83, 0x57, 0x11, 0x7f, 0x42, 0x45, 0xfc,
	0x32, 0x26, 0x63, 0xdd, 0xf2, 0xf9, 0x33, 0xaa, 0xd2, 0xa8, 0xb8, 0xe1, 0x06, 0xa7, 0x03, 0xd0,
	0x6d, 0xf0, 0x2b, 0x4a, 0x35, 0x48, 0x0a, 0xe3, 0x4d, 0x65, 0x7c, 0xaa, 0x1e, 0x7d, 0x06, 0x9d,
	0x88, 0x11, 0x2d, 0x1b, 0x66, 0x49, 0x2c, 0xfc, 0x86, 0xb2, 0x58, 0x92, 0xa2, 0x63, 0xd8, 0x2b,
	0x24, 0x01, 0xc9, 0x92, 0x78, 0x14, 0x09, 0x32, 0xf6, 0xb7, 0x14, 0x78, 0x9d, 0x0a, 0x7d, 0x0e,
	0xbb, 0x85, 0x78, 0x10, 0xe5, 0x93, 0x57, 0xe2, 0x79, 0xe6, 0x37, 0x15, 0x7e, 0x55, 0xb1, 0x14,
	0x43, 0x25, 0x40, 0x9a, 0xf9, 0xee, 0x4a, 0x0c, 0x0b, 0x7a, 0x74, 0x0b, 0x2e, 0xae, 0x8d, 0x8f,
	0x66, 0x7e, 0x4b, 0x99, 0x9e, 0xa6, 0xee, 0xff, 0xe3, 0x80, 0xf7, 0x42, 0x2e, 0xfb, 0x8f, 0x23,
	0x45, 0xa2, 0x3b, 0x92, 0x21, 0x93, 0x58, 0x3d, 0xae, 0xc4, 0x21, 0x54, 0x8c, 0xe6, 0x62, 0x02,
	0x77, 0x2f, 0x14, 0x32, 0xbb, 0x9a, 0x6f, 0xf4, 0x9c, 0x63, 0x07, 0x7d, 0x25, 0x89, 0xa0, 0x8d,
	0xb5, 0x7f, 0x68, 0xaf, 0x5c, 0x94, 0x4b, 0xf3, 0xdd, 0x95, 0xed, 0xd9, 0xd8, 0x5f, 0x07, 0x90,
	0xc4, 0xd7, 0x0e, 0x22, 0xd5, 0x34, 0x2a, 0x85, 0xa3, 0x3f, 0x5b, 0xad, 0x0c, 0xbc, 0x81, 0x6e,
	0x5b, 0x46, 0xdb, 0x65, 0x6f, 0xd7, 0x4c, 0xe5, 0x92, 0xe4, 0x5d, 0x54, 0x8a, 0x2c, 0x43, 0xf1,
	0xc6, 0xb1, 0xd3, 0xff, 0x09, 0x40, 0x85, 0xae, 0x03, 0xfd, 0x04, 0x36, 0x65, 0xe9, 0xa3, 0x85,
	0x0e, 0xd8, 0x6d, 0xc9, 0x93, 0x5e, 0x22, 0x36, 0x7a, 0x0e, 0xba, 0x06, 0xae, 0xed, 0x0f, 0x3a,
	0x33, 0x8b, 0xdd, 0x62, 0x01, 0xde, 0xbf, 0x69, 0x52, 0x1b, 0x90, 0x68, 0x4c, 0x18, 0xea, 0x41,
	0x5d, 0xb6, 0xb0, 0xa5, 0x11, 0xdf, 0x5d, 0xee, 0x8d, 0x15, 0xc3, 0x6f, 0x59, 0x2c, 0xb4, 0xe1,
	0xd3, 0xdc, 0x18, 0x96, 0xb3, 0xba, 0xbb, 0xdc, 0x77, 0xf1, 0xc6, 0xc9, 0x96, 0xfa, 0xc7, 0x76,
	0xe3, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1b, 0xd1, 0x7a, 0x21, 0xc0, 0x0d, 0x00, 0x00,
}
