// Code generated by protoc-gen-go.
// source: vasto.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	vasto.proto

It has these top-level messages:
	BalanceRequest
	StoreMessage
	ClientMessage
	Cluster
	ClusterNode
	StoreResource
	StoreStatusInCluster
	ShardStatus
	StoreHeartbeat
	ClientHeartbeat
	Empty
	Requests
	Responses
	Request
	PutRequest
	PutResponse
	DeleteRequest
	DeleteResponse
	GetRequest
	GetResponse
	GetByPrefixRequest
	GetByPrefixResponse
	Response
	KeyValue
	CopyDoneMessge
	BootstrapCopyRequest
	BootstrapCopyResponse
	PullUpdateRequest
	PullUpdateResponse
	UpdateEntry
	CheckBinlogRequest
	CheckBinlogResponse
	DescribeRequest
	DescribeResponse
	CreateClusterRequest
	CreateClusterResponse
	DeleteClusterRequest
	DeleteClusterResponse
	CreateShardRequest
	CreateShardResponse
	DeleteKeyspaceRequest
	DeleteKeyspaceResponse
	ResizeRequest
	ResizeProgress
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ShardStatus_Status int32

const (
	ShardStatus_EMPTY     ShardStatus_Status = 0
	ShardStatus_BOOTSTRAP ShardStatus_Status = 1
	ShardStatus_READY     ShardStatus_Status = 2
	ShardStatus_DELETED   ShardStatus_Status = 3
)

var ShardStatus_Status_name = map[int32]string{
	0: "EMPTY",
	1: "BOOTSTRAP",
	2: "READY",
	3: "DELETED",
}
var ShardStatus_Status_value = map[string]int32{
	"EMPTY":     0,
	"BOOTSTRAP": 1,
	"READY":     2,
	"DELETED":   3,
}

func (x ShardStatus_Status) String() string {
	return proto.EnumName(ShardStatus_Status_name, int32(x))
}
func (ShardStatus_Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{7, 0} }

// ////////////////////////////////////////////////
// 1. master received request to balance the data
type BalanceRequest struct {
	DataCenter string `protobuf:"bytes,1,opt,name=data_center,json=dataCenter" json:"data_center,omitempty"`
	StoreGroup string `protobuf:"bytes,2,opt,name=store_group,json=storeGroup" json:"store_group,omitempty"`
	StoreCount uint32 `protobuf:"varint,3,opt,name=store_count,json=storeCount" json:"store_count,omitempty"`
}

func (m *BalanceRequest) Reset()                    { *m = BalanceRequest{} }
func (m *BalanceRequest) String() string            { return proto.CompactTextString(m) }
func (*BalanceRequest) ProtoMessage()               {}
func (*BalanceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *BalanceRequest) GetDataCenter() string {
	if m != nil {
		return m.DataCenter
	}
	return ""
}

func (m *BalanceRequest) GetStoreGroup() string {
	if m != nil {
		return m.StoreGroup
	}
	return ""
}

func (m *BalanceRequest) GetStoreCount() uint32 {
	if m != nil {
		return m.StoreCount
	}
	return 0
}

type StoreMessage struct {
}

func (m *StoreMessage) Reset()                    { *m = StoreMessage{} }
func (m *StoreMessage) String() string            { return proto.CompactTextString(m) }
func (*StoreMessage) ProtoMessage()               {}
func (*StoreMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type ClientMessage struct {
	Cluster *Cluster                           `protobuf:"bytes,1,opt,name=cluster" json:"cluster,omitempty"`
	Updates *ClientMessage_StoreResourceUpdate `protobuf:"bytes,2,opt,name=updates" json:"updates,omitempty"`
	Resize  *ClientMessage_Resize              `protobuf:"bytes,3,opt,name=resize" json:"resize,omitempty"`
}

func (m *ClientMessage) Reset()                    { *m = ClientMessage{} }
func (m *ClientMessage) String() string            { return proto.CompactTextString(m) }
func (*ClientMessage) ProtoMessage()               {}
func (*ClientMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ClientMessage) GetCluster() *Cluster {
	if m != nil {
		return m.Cluster
	}
	return nil
}

func (m *ClientMessage) GetUpdates() *ClientMessage_StoreResourceUpdate {
	if m != nil {
		return m.Updates
	}
	return nil
}

func (m *ClientMessage) GetResize() *ClientMessage_Resize {
	if m != nil {
		return m.Resize
	}
	return nil
}

type ClientMessage_StoreResourceUpdate struct {
	Nodes    []*ClusterNode `protobuf:"bytes,1,rep,name=nodes" json:"nodes,omitempty"`
	IsDelete bool           `protobuf:"varint,2,opt,name=is_delete,json=isDelete" json:"is_delete,omitempty"`
	Keyspace string         `protobuf:"bytes,3,opt,name=keyspace" json:"keyspace,omitempty"`
}

func (m *ClientMessage_StoreResourceUpdate) Reset()         { *m = ClientMessage_StoreResourceUpdate{} }
func (m *ClientMessage_StoreResourceUpdate) String() string { return proto.CompactTextString(m) }
func (*ClientMessage_StoreResourceUpdate) ProtoMessage()    {}
func (*ClientMessage_StoreResourceUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{2, 0}
}

func (m *ClientMessage_StoreResourceUpdate) GetNodes() []*ClusterNode {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *ClientMessage_StoreResourceUpdate) GetIsDelete() bool {
	if m != nil {
		return m.IsDelete
	}
	return false
}

func (m *ClientMessage_StoreResourceUpdate) GetKeyspace() string {
	if m != nil {
		return m.Keyspace
	}
	return ""
}

type ClientMessage_Resize struct {
	CurrentClusterSize uint32 `protobuf:"varint,1,opt,name=current_cluster_size,json=currentClusterSize" json:"current_cluster_size,omitempty"`
	NextClusterSize    uint32 `protobuf:"varint,2,opt,name=next_cluster_size,json=nextClusterSize" json:"next_cluster_size,omitempty"`
	Keyspace           string `protobuf:"bytes,3,opt,name=keyspace" json:"keyspace,omitempty"`
}

func (m *ClientMessage_Resize) Reset()                    { *m = ClientMessage_Resize{} }
func (m *ClientMessage_Resize) String() string            { return proto.CompactTextString(m) }
func (*ClientMessage_Resize) ProtoMessage()               {}
func (*ClientMessage_Resize) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 1} }

func (m *ClientMessage_Resize) GetCurrentClusterSize() uint32 {
	if m != nil {
		return m.CurrentClusterSize
	}
	return 0
}

func (m *ClientMessage_Resize) GetNextClusterSize() uint32 {
	if m != nil {
		return m.NextClusterSize
	}
	return 0
}

func (m *ClientMessage_Resize) GetKeyspace() string {
	if m != nil {
		return m.Keyspace
	}
	return ""
}

type Cluster struct {
	Keyspace            string         `protobuf:"bytes,1,opt,name=keyspace" json:"keyspace,omitempty"`
	DataCenter          string         `protobuf:"bytes,2,opt,name=data_center,json=dataCenter" json:"data_center,omitempty"`
	Nodes               []*ClusterNode `protobuf:"bytes,3,rep,name=nodes" json:"nodes,omitempty"`
	ExpectedClusterSize uint32         `protobuf:"varint,4,opt,name=expected_cluster_size,json=expectedClusterSize" json:"expected_cluster_size,omitempty"`
	CurrentClusterSize  uint32         `protobuf:"varint,5,opt,name=current_cluster_size,json=currentClusterSize" json:"current_cluster_size,omitempty"`
	NextClusterSize     uint32         `protobuf:"varint,6,opt,name=next_cluster_size,json=nextClusterSize" json:"next_cluster_size,omitempty"`
	ReplicationFactor   uint32         `protobuf:"varint,7,opt,name=replication_factor,json=replicationFactor" json:"replication_factor,omitempty"`
}

func (m *Cluster) Reset()                    { *m = Cluster{} }
func (m *Cluster) String() string            { return proto.CompactTextString(m) }
func (*Cluster) ProtoMessage()               {}
func (*Cluster) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Cluster) GetKeyspace() string {
	if m != nil {
		return m.Keyspace
	}
	return ""
}

func (m *Cluster) GetDataCenter() string {
	if m != nil {
		return m.DataCenter
	}
	return ""
}

func (m *Cluster) GetNodes() []*ClusterNode {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *Cluster) GetExpectedClusterSize() uint32 {
	if m != nil {
		return m.ExpectedClusterSize
	}
	return 0
}

func (m *Cluster) GetCurrentClusterSize() uint32 {
	if m != nil {
		return m.CurrentClusterSize
	}
	return 0
}

func (m *Cluster) GetNextClusterSize() uint32 {
	if m != nil {
		return m.NextClusterSize
	}
	return 0
}

func (m *Cluster) GetReplicationFactor() uint32 {
	if m != nil {
		return m.ReplicationFactor
	}
	return 0
}

// denormalized
type ClusterNode struct {
	StoreResource *StoreResource `protobuf:"bytes,1,opt,name=store_resource,json=storeResource" json:"store_resource,omitempty"`
	ShardStatus   *ShardStatus   `protobuf:"bytes,2,opt,name=shard_status,json=shardStatus" json:"shard_status,omitempty"`
}

func (m *ClusterNode) Reset()                    { *m = ClusterNode{} }
func (m *ClusterNode) String() string            { return proto.CompactTextString(m) }
func (*ClusterNode) ProtoMessage()               {}
func (*ClusterNode) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ClusterNode) GetStoreResource() *StoreResource {
	if m != nil {
		return m.StoreResource
	}
	return nil
}

func (m *ClusterNode) GetShardStatus() *ShardStatus {
	if m != nil {
		return m.ShardStatus
	}
	return nil
}

type StoreResource struct {
	DataCenter      string   `protobuf:"bytes,1,opt,name=data_center,json=dataCenter" json:"data_center,omitempty"`
	Network         string   `protobuf:"bytes,2,opt,name=network" json:"network,omitempty"`
	Address         string   `protobuf:"bytes,3,opt,name=address" json:"address,omitempty"`
	AdminAddress    string   `protobuf:"bytes,4,opt,name=admin_address,json=adminAddress" json:"admin_address,omitempty"`
	Tags            []string `protobuf:"bytes,7,rep,name=tags" json:"tags,omitempty"`
	DiskSizeGb      uint32   `protobuf:"varint,8,opt,name=disk_size_gb,json=diskSizeGb" json:"disk_size_gb,omitempty"`
	AllocatedSizeGb uint32   `protobuf:"varint,9,opt,name=allocated_size_gb,json=allocatedSizeGb" json:"allocated_size_gb,omitempty"`
}

func (m *StoreResource) Reset()                    { *m = StoreResource{} }
func (m *StoreResource) String() string            { return proto.CompactTextString(m) }
func (*StoreResource) ProtoMessage()               {}
func (*StoreResource) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *StoreResource) GetDataCenter() string {
	if m != nil {
		return m.DataCenter
	}
	return ""
}

func (m *StoreResource) GetNetwork() string {
	if m != nil {
		return m.Network
	}
	return ""
}

func (m *StoreResource) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *StoreResource) GetAdminAddress() string {
	if m != nil {
		return m.AdminAddress
	}
	return ""
}

func (m *StoreResource) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *StoreResource) GetDiskSizeGb() uint32 {
	if m != nil {
		return m.DiskSizeGb
	}
	return 0
}

func (m *StoreResource) GetAllocatedSizeGb() uint32 {
	if m != nil {
		return m.AllocatedSizeGb
	}
	return 0
}

// StoreStatusInCluster is saved to and load from disk
type StoreStatusInCluster struct {
	Id            uint32                  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	ShardStatuses map[uint32]*ShardStatus `protobuf:"bytes,2,rep,name=shard_statuses,json=shardStatuses" json:"shard_statuses,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// duplicated info, need to validate on master when reconvene
	ClusterSize uint32 `protobuf:"varint,3,opt,name=cluster_size,json=clusterSize" json:"cluster_size,omitempty"`
	// duplicated info, need to validate on master when reconvene
	ReplicationFactor uint32 `protobuf:"varint,4,opt,name=replication_factor,json=replicationFactor" json:"replication_factor,omitempty"`
}

func (m *StoreStatusInCluster) Reset()                    { *m = StoreStatusInCluster{} }
func (m *StoreStatusInCluster) String() string            { return proto.CompactTextString(m) }
func (*StoreStatusInCluster) ProtoMessage()               {}
func (*StoreStatusInCluster) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *StoreStatusInCluster) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *StoreStatusInCluster) GetShardStatuses() map[uint32]*ShardStatus {
	if m != nil {
		return m.ShardStatuses
	}
	return nil
}

func (m *StoreStatusInCluster) GetClusterSize() uint32 {
	if m != nil {
		return m.ClusterSize
	}
	return 0
}

func (m *StoreStatusInCluster) GetReplicationFactor() uint32 {
	if m != nil {
		return m.ReplicationFactor
	}
	return 0
}

type ShardStatus struct {
	KeyspaceName      string             `protobuf:"bytes,1,opt,name=keyspace_name,json=keyspaceName" json:"keyspace_name,omitempty"`
	NodeId            uint32             `protobuf:"varint,2,opt,name=node_id,json=nodeId" json:"node_id,omitempty"`
	ShardId           uint32             `protobuf:"varint,3,opt,name=shard_id,json=shardId" json:"shard_id,omitempty"`
	ClusterSize       uint32             `protobuf:"varint,4,opt,name=cluster_size,json=clusterSize" json:"cluster_size,omitempty"`
	ReplicationFactor uint32             `protobuf:"varint,5,opt,name=replication_factor,json=replicationFactor" json:"replication_factor,omitempty"`
	Status            ShardStatus_Status `protobuf:"varint,6,opt,name=status,enum=pb.ShardStatus_Status" json:"status,omitempty"`
}

func (m *ShardStatus) Reset()                    { *m = ShardStatus{} }
func (m *ShardStatus) String() string            { return proto.CompactTextString(m) }
func (*ShardStatus) ProtoMessage()               {}
func (*ShardStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ShardStatus) GetKeyspaceName() string {
	if m != nil {
		return m.KeyspaceName
	}
	return ""
}

func (m *ShardStatus) GetNodeId() uint32 {
	if m != nil {
		return m.NodeId
	}
	return 0
}

func (m *ShardStatus) GetShardId() uint32 {
	if m != nil {
		return m.ShardId
	}
	return 0
}

func (m *ShardStatus) GetClusterSize() uint32 {
	if m != nil {
		return m.ClusterSize
	}
	return 0
}

func (m *ShardStatus) GetReplicationFactor() uint32 {
	if m != nil {
		return m.ReplicationFactor
	}
	return 0
}

func (m *ShardStatus) GetStatus() ShardStatus_Status {
	if m != nil {
		return m.Status
	}
	return ShardStatus_EMPTY
}

// ////////////////////////////////////////////////
type StoreHeartbeat struct {
	// only in the initial heartbeat
	StoreResource *StoreResource `protobuf:"bytes,1,opt,name=store_resource,json=storeResource" json:"store_resource,omitempty"`
	// sent to master one at a time, after the initial heartbeat
	ShardStatus *ShardStatus `protobuf:"bytes,2,opt,name=shardStatus" json:"shardStatus,omitempty"`
}

func (m *StoreHeartbeat) Reset()                    { *m = StoreHeartbeat{} }
func (m *StoreHeartbeat) String() string            { return proto.CompactTextString(m) }
func (*StoreHeartbeat) ProtoMessage()               {}
func (*StoreHeartbeat) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *StoreHeartbeat) GetStoreResource() *StoreResource {
	if m != nil {
		return m.StoreResource
	}
	return nil
}

func (m *StoreHeartbeat) GetShardStatus() *ShardStatus {
	if m != nil {
		return m.ShardStatus
	}
	return nil
}

type ClientHeartbeat struct {
	DataCenter string `protobuf:"bytes,1,opt,name=data_center,json=dataCenter" json:"data_center,omitempty"`
	Keyspace   string `protobuf:"bytes,2,opt,name=keyspace" json:"keyspace,omitempty"`
	IsUnfollow bool   `protobuf:"varint,3,opt,name=is_unfollow,json=isUnfollow" json:"is_unfollow,omitempty"`
}

func (m *ClientHeartbeat) Reset()                    { *m = ClientHeartbeat{} }
func (m *ClientHeartbeat) String() string            { return proto.CompactTextString(m) }
func (*ClientHeartbeat) ProtoMessage()               {}
func (*ClientHeartbeat) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *ClientHeartbeat) GetDataCenter() string {
	if m != nil {
		return m.DataCenter
	}
	return ""
}

func (m *ClientHeartbeat) GetKeyspace() string {
	if m != nil {
		return m.Keyspace
	}
	return ""
}

func (m *ClientHeartbeat) GetIsUnfollow() bool {
	if m != nil {
		return m.IsUnfollow
	}
	return false
}

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

// ////////////////////////////////////////////////
// // data queries
// ////////////////////////////////////////////////
type Requests struct {
	Keyspace string     `protobuf:"bytes,1,opt,name=keyspace" json:"keyspace,omitempty"`
	Requests []*Request `protobuf:"bytes,2,rep,name=requests" json:"requests,omitempty"`
}

func (m *Requests) Reset()                    { *m = Requests{} }
func (m *Requests) String() string            { return proto.CompactTextString(m) }
func (*Requests) ProtoMessage()               {}
func (*Requests) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *Requests) GetKeyspace() string {
	if m != nil {
		return m.Keyspace
	}
	return ""
}

func (m *Requests) GetRequests() []*Request {
	if m != nil {
		return m.Requests
	}
	return nil
}

type Responses struct {
	Responses []*Response `protobuf:"bytes,1,rep,name=responses" json:"responses,omitempty"`
}

func (m *Responses) Reset()                    { *m = Responses{} }
func (m *Responses) String() string            { return proto.CompactTextString(m) }
func (*Responses) ProtoMessage()               {}
func (*Responses) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *Responses) GetResponses() []*Response {
	if m != nil {
		return m.Responses
	}
	return nil
}

type Request struct {
	Put         *PutRequest         `protobuf:"bytes,1,opt,name=put" json:"put,omitempty"`
	Get         *GetRequest         `protobuf:"bytes,2,opt,name=get" json:"get,omitempty"`
	GetByPrefix *GetByPrefixRequest `protobuf:"bytes,3,opt,name=get_by_prefix,json=getByPrefix" json:"get_by_prefix,omitempty"`
	Delete      *DeleteRequest      `protobuf:"bytes,4,opt,name=delete" json:"delete,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *Request) GetPut() *PutRequest {
	if m != nil {
		return m.Put
	}
	return nil
}

func (m *Request) GetGet() *GetRequest {
	if m != nil {
		return m.Get
	}
	return nil
}

func (m *Request) GetGetByPrefix() *GetByPrefixRequest {
	if m != nil {
		return m.GetByPrefix
	}
	return nil
}

func (m *Request) GetDelete() *DeleteRequest {
	if m != nil {
		return m.Delete
	}
	return nil
}

type PutRequest struct {
	Replica       uint32    `protobuf:"varint,1,opt,name=replica" json:"replica,omitempty"`
	PartitionHash uint64    `protobuf:"varint,2,opt,name=partition_hash,json=partitionHash" json:"partition_hash,omitempty"`
	KeyValue      *KeyValue `protobuf:"bytes,3,opt,name=key_value,json=keyValue" json:"key_value,omitempty"`
	TtlSecond     uint32    `protobuf:"varint,4,opt,name=ttl_second,json=ttlSecond" json:"ttl_second,omitempty"`
}

func (m *PutRequest) Reset()                    { *m = PutRequest{} }
func (m *PutRequest) String() string            { return proto.CompactTextString(m) }
func (*PutRequest) ProtoMessage()               {}
func (*PutRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *PutRequest) GetReplica() uint32 {
	if m != nil {
		return m.Replica
	}
	return 0
}

func (m *PutRequest) GetPartitionHash() uint64 {
	if m != nil {
		return m.PartitionHash
	}
	return 0
}

func (m *PutRequest) GetKeyValue() *KeyValue {
	if m != nil {
		return m.KeyValue
	}
	return nil
}

func (m *PutRequest) GetTtlSecond() uint32 {
	if m != nil {
		return m.TtlSecond
	}
	return 0
}

type PutResponse struct {
	Ok     bool   `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
	Status string `protobuf:"bytes,2,opt,name=status" json:"status,omitempty"`
}

func (m *PutResponse) Reset()                    { *m = PutResponse{} }
func (m *PutResponse) String() string            { return proto.CompactTextString(m) }
func (*PutResponse) ProtoMessage()               {}
func (*PutResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *PutResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *PutResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type DeleteRequest struct {
	Replica       uint32 `protobuf:"varint,1,opt,name=replica" json:"replica,omitempty"`
	PartitionHash uint64 `protobuf:"varint,2,opt,name=partition_hash,json=partitionHash" json:"partition_hash,omitempty"`
	Key           []byte `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
}

func (m *DeleteRequest) Reset()                    { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()               {}
func (*DeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *DeleteRequest) GetReplica() uint32 {
	if m != nil {
		return m.Replica
	}
	return 0
}

func (m *DeleteRequest) GetPartitionHash() uint64 {
	if m != nil {
		return m.PartitionHash
	}
	return 0
}

func (m *DeleteRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type DeleteResponse struct {
	Ok     bool   `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
	Status string `protobuf:"bytes,2,opt,name=status" json:"status,omitempty"`
}

func (m *DeleteResponse) Reset()                    { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()               {}
func (*DeleteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *DeleteResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *DeleteResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type GetRequest struct {
	Replica uint32 `protobuf:"varint,1,opt,name=replica" json:"replica,omitempty"`
	Key     []byte `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (m *GetRequest) Reset()                    { *m = GetRequest{} }
func (m *GetRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()               {}
func (*GetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *GetRequest) GetReplica() uint32 {
	if m != nil {
		return m.Replica
	}
	return 0
}

func (m *GetRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type GetResponse struct {
	Ok       bool      `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
	Status   string    `protobuf:"bytes,2,opt,name=status" json:"status,omitempty"`
	KeyValue *KeyValue `protobuf:"bytes,3,opt,name=key_value,json=keyValue" json:"key_value,omitempty"`
}

func (m *GetResponse) Reset()                    { *m = GetResponse{} }
func (m *GetResponse) String() string            { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()               {}
func (*GetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *GetResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *GetResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *GetResponse) GetKeyValue() *KeyValue {
	if m != nil {
		return m.KeyValue
	}
	return nil
}

type GetByPrefixRequest struct {
	Replica     uint32 `protobuf:"varint,1,opt,name=replica" json:"replica,omitempty"`
	Prefix      []byte `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Limit       uint32 `protobuf:"varint,3,opt,name=limit" json:"limit,omitempty"`
	LastSeenKey []byte `protobuf:"bytes,4,opt,name=last_seen_key,json=lastSeenKey,proto3" json:"last_seen_key,omitempty"`
}

func (m *GetByPrefixRequest) Reset()                    { *m = GetByPrefixRequest{} }
func (m *GetByPrefixRequest) String() string            { return proto.CompactTextString(m) }
func (*GetByPrefixRequest) ProtoMessage()               {}
func (*GetByPrefixRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *GetByPrefixRequest) GetReplica() uint32 {
	if m != nil {
		return m.Replica
	}
	return 0
}

func (m *GetByPrefixRequest) GetPrefix() []byte {
	if m != nil {
		return m.Prefix
	}
	return nil
}

func (m *GetByPrefixRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetByPrefixRequest) GetLastSeenKey() []byte {
	if m != nil {
		return m.LastSeenKey
	}
	return nil
}

type GetByPrefixResponse struct {
	Ok        bool        `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
	Status    string      `protobuf:"bytes,2,opt,name=status" json:"status,omitempty"`
	KeyValues []*KeyValue `protobuf:"bytes,3,rep,name=key_values,json=keyValues" json:"key_values,omitempty"`
}

func (m *GetByPrefixResponse) Reset()                    { *m = GetByPrefixResponse{} }
func (m *GetByPrefixResponse) String() string            { return proto.CompactTextString(m) }
func (*GetByPrefixResponse) ProtoMessage()               {}
func (*GetByPrefixResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *GetByPrefixResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *GetByPrefixResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *GetByPrefixResponse) GetKeyValues() []*KeyValue {
	if m != nil {
		return m.KeyValues
	}
	return nil
}

type Response struct {
	Put         *PutResponse         `protobuf:"bytes,1,opt,name=put" json:"put,omitempty"`
	Get         *GetResponse         `protobuf:"bytes,2,opt,name=get" json:"get,omitempty"`
	GetByPrefix *GetByPrefixResponse `protobuf:"bytes,3,opt,name=get_by_prefix,json=getByPrefix" json:"get_by_prefix,omitempty"`
	Delete      *DeleteResponse      `protobuf:"bytes,4,opt,name=delete" json:"delete,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *Response) GetPut() *PutResponse {
	if m != nil {
		return m.Put
	}
	return nil
}

func (m *Response) GetGet() *GetResponse {
	if m != nil {
		return m.Get
	}
	return nil
}

func (m *Response) GetGetByPrefix() *GetByPrefixResponse {
	if m != nil {
		return m.GetByPrefix
	}
	return nil
}

func (m *Response) GetDelete() *DeleteResponse {
	if m != nil {
		return m.Delete
	}
	return nil
}

type KeyValue struct {
	Key   []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *KeyValue) Reset()                    { *m = KeyValue{} }
func (m *KeyValue) String() string            { return proto.CompactTextString(m) }
func (*KeyValue) ProtoMessage()               {}
func (*KeyValue) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *KeyValue) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *KeyValue) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

// ////////////////////////////////////////////////
// // data copying
// ////////////////////////////////////////////////
type CopyDoneMessge struct {
	Shard           int32 `protobuf:"varint,1,opt,name=shard" json:"shard,omitempty"`
	CopyStartTimeNs int64 `protobuf:"varint,2,opt,name=copy_start_time_ns,json=copyStartTimeNs" json:"copy_start_time_ns,omitempty"`
}

func (m *CopyDoneMessge) Reset()                    { *m = CopyDoneMessge{} }
func (m *CopyDoneMessge) String() string            { return proto.CompactTextString(m) }
func (*CopyDoneMessge) ProtoMessage()               {}
func (*CopyDoneMessge) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *CopyDoneMessge) GetShard() int32 {
	if m != nil {
		return m.Shard
	}
	return 0
}

func (m *CopyDoneMessge) GetCopyStartTimeNs() int64 {
	if m != nil {
		return m.CopyStartTimeNs
	}
	return 0
}

type BootstrapCopyRequest struct {
	Keyspace string `protobuf:"bytes,1,opt,name=keyspace" json:"keyspace,omitempty"`
	NodeId   uint32 `protobuf:"varint,2,opt,name=node_id,json=nodeId" json:"node_id,omitempty"`
}

func (m *BootstrapCopyRequest) Reset()                    { *m = BootstrapCopyRequest{} }
func (m *BootstrapCopyRequest) String() string            { return proto.CompactTextString(m) }
func (*BootstrapCopyRequest) ProtoMessage()               {}
func (*BootstrapCopyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *BootstrapCopyRequest) GetKeyspace() string {
	if m != nil {
		return m.Keyspace
	}
	return ""
}

func (m *BootstrapCopyRequest) GetNodeId() uint32 {
	if m != nil {
		return m.NodeId
	}
	return 0
}

type BootstrapCopyResponse struct {
	KeyValues          []*KeyValue                               `protobuf:"bytes,1,rep,name=key_values,json=keyValues" json:"key_values,omitempty"`
	BinlogTailProgress *BootstrapCopyResponse_BinlogTailProgress `protobuf:"bytes,2,opt,name=binlogTailProgress" json:"binlogTailProgress,omitempty"`
}

func (m *BootstrapCopyResponse) Reset()                    { *m = BootstrapCopyResponse{} }
func (m *BootstrapCopyResponse) String() string            { return proto.CompactTextString(m) }
func (*BootstrapCopyResponse) ProtoMessage()               {}
func (*BootstrapCopyResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *BootstrapCopyResponse) GetKeyValues() []*KeyValue {
	if m != nil {
		return m.KeyValues
	}
	return nil
}

func (m *BootstrapCopyResponse) GetBinlogTailProgress() *BootstrapCopyResponse_BinlogTailProgress {
	if m != nil {
		return m.BinlogTailProgress
	}
	return nil
}

// this message is only sent at the end of copying
type BootstrapCopyResponse_BinlogTailProgress struct {
	Segment uint32 `protobuf:"varint,1,opt,name=segment" json:"segment,omitempty"`
	Offset  uint64 `protobuf:"varint,2,opt,name=offset" json:"offset,omitempty"`
}

func (m *BootstrapCopyResponse_BinlogTailProgress) Reset() {
	*m = BootstrapCopyResponse_BinlogTailProgress{}
}
func (m *BootstrapCopyResponse_BinlogTailProgress) String() string { return proto.CompactTextString(m) }
func (*BootstrapCopyResponse_BinlogTailProgress) ProtoMessage()    {}
func (*BootstrapCopyResponse_BinlogTailProgress) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{26, 0}
}

func (m *BootstrapCopyResponse_BinlogTailProgress) GetSegment() uint32 {
	if m != nil {
		return m.Segment
	}
	return 0
}

func (m *BootstrapCopyResponse_BinlogTailProgress) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type PullUpdateRequest struct {
	Keyspace string `protobuf:"bytes,1,opt,name=keyspace" json:"keyspace,omitempty"`
	NodeId   uint32 `protobuf:"varint,2,opt,name=node_id,json=nodeId" json:"node_id,omitempty"`
	Segment  uint32 `protobuf:"varint,3,opt,name=segment" json:"segment,omitempty"`
	Offset   uint64 `protobuf:"varint,4,opt,name=offset" json:"offset,omitempty"`
	Limit    uint32 `protobuf:"varint,5,opt,name=limit" json:"limit,omitempty"`
}

func (m *PullUpdateRequest) Reset()                    { *m = PullUpdateRequest{} }
func (m *PullUpdateRequest) String() string            { return proto.CompactTextString(m) }
func (*PullUpdateRequest) ProtoMessage()               {}
func (*PullUpdateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *PullUpdateRequest) GetKeyspace() string {
	if m != nil {
		return m.Keyspace
	}
	return ""
}

func (m *PullUpdateRequest) GetNodeId() uint32 {
	if m != nil {
		return m.NodeId
	}
	return 0
}

func (m *PullUpdateRequest) GetSegment() uint32 {
	if m != nil {
		return m.Segment
	}
	return 0
}

func (m *PullUpdateRequest) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *PullUpdateRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type PullUpdateResponse struct {
	NextSegment uint32         `protobuf:"varint,1,opt,name=next_segment,json=nextSegment" json:"next_segment,omitempty"`
	NextOffset  uint64         `protobuf:"varint,2,opt,name=next_offset,json=nextOffset" json:"next_offset,omitempty"`
	Entries     []*UpdateEntry `protobuf:"bytes,3,rep,name=entries" json:"entries,omitempty"`
	OutOfSync   bool           `protobuf:"varint,4,opt,name=out_of_sync,json=outOfSync" json:"out_of_sync,omitempty"`
}

func (m *PullUpdateResponse) Reset()                    { *m = PullUpdateResponse{} }
func (m *PullUpdateResponse) String() string            { return proto.CompactTextString(m) }
func (*PullUpdateResponse) ProtoMessage()               {}
func (*PullUpdateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

func (m *PullUpdateResponse) GetNextSegment() uint32 {
	if m != nil {
		return m.NextSegment
	}
	return 0
}

func (m *PullUpdateResponse) GetNextOffset() uint64 {
	if m != nil {
		return m.NextOffset
	}
	return 0
}

func (m *PullUpdateResponse) GetEntries() []*UpdateEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

func (m *PullUpdateResponse) GetOutOfSync() bool {
	if m != nil {
		return m.OutOfSync
	}
	return false
}

type UpdateEntry struct {
	PartitionHash uint64 `protobuf:"varint,3,opt,name=partition_hash,json=partitionHash" json:"partition_hash,omitempty"`
	UpdatedAtNs   uint64 `protobuf:"varint,4,opt,name=updated_at_ns,json=updatedAtNs" json:"updated_at_ns,omitempty"`
	TtlSecond     uint32 `protobuf:"varint,5,opt,name=ttl_second,json=ttlSecond" json:"ttl_second,omitempty"`
	Crc           uint32 `protobuf:"varint,6,opt,name=crc" json:"crc,omitempty"`
	IsDelete      bool   `protobuf:"varint,7,opt,name=isDelete" json:"isDelete,omitempty"`
	Key           []byte `protobuf:"bytes,8,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte `protobuf:"bytes,9,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *UpdateEntry) Reset()                    { *m = UpdateEntry{} }
func (m *UpdateEntry) String() string            { return proto.CompactTextString(m) }
func (*UpdateEntry) ProtoMessage()               {}
func (*UpdateEntry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

func (m *UpdateEntry) GetPartitionHash() uint64 {
	if m != nil {
		return m.PartitionHash
	}
	return 0
}

func (m *UpdateEntry) GetUpdatedAtNs() uint64 {
	if m != nil {
		return m.UpdatedAtNs
	}
	return 0
}

func (m *UpdateEntry) GetTtlSecond() uint32 {
	if m != nil {
		return m.TtlSecond
	}
	return 0
}

func (m *UpdateEntry) GetCrc() uint32 {
	if m != nil {
		return m.Crc
	}
	return 0
}

func (m *UpdateEntry) GetIsDelete() bool {
	if m != nil {
		return m.IsDelete
	}
	return false
}

func (m *UpdateEntry) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *UpdateEntry) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type CheckBinlogRequest struct {
	Keyspace string `protobuf:"bytes,1,opt,name=keyspace" json:"keyspace,omitempty"`
	NodeId   uint32 `protobuf:"varint,2,opt,name=node_id,json=nodeId" json:"node_id,omitempty"`
}

func (m *CheckBinlogRequest) Reset()                    { *m = CheckBinlogRequest{} }
func (m *CheckBinlogRequest) String() string            { return proto.CompactTextString(m) }
func (*CheckBinlogRequest) ProtoMessage()               {}
func (*CheckBinlogRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{30} }

func (m *CheckBinlogRequest) GetKeyspace() string {
	if m != nil {
		return m.Keyspace
	}
	return ""
}

func (m *CheckBinlogRequest) GetNodeId() uint32 {
	if m != nil {
		return m.NodeId
	}
	return 0
}

type CheckBinlogResponse struct {
	NodeId          uint32 `protobuf:"varint,1,opt,name=node_id,json=nodeId" json:"node_id,omitempty"`
	EarliestSegment uint32 `protobuf:"varint,2,opt,name=earliest_segment,json=earliestSegment" json:"earliest_segment,omitempty"`
	LatestSegment   uint32 `protobuf:"varint,3,opt,name=latest_segment,json=latestSegment" json:"latest_segment,omitempty"`
}

func (m *CheckBinlogResponse) Reset()                    { *m = CheckBinlogResponse{} }
func (m *CheckBinlogResponse) String() string            { return proto.CompactTextString(m) }
func (*CheckBinlogResponse) ProtoMessage()               {}
func (*CheckBinlogResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{31} }

func (m *CheckBinlogResponse) GetNodeId() uint32 {
	if m != nil {
		return m.NodeId
	}
	return 0
}

func (m *CheckBinlogResponse) GetEarliestSegment() uint32 {
	if m != nil {
		return m.EarliestSegment
	}
	return 0
}

func (m *CheckBinlogResponse) GetLatestSegment() uint32 {
	if m != nil {
		return m.LatestSegment
	}
	return 0
}

// ////////////////////////////////////////////////
// // admin
// ////////////////////////////////////////////////
type DescribeRequest struct {
	DescDataCenters *DescribeRequest_DescDataCenters `protobuf:"bytes,1,opt,name=desc_data_centers,json=descDataCenters" json:"desc_data_centers,omitempty"`
	DescKeyspaces   *DescribeRequest_DescKeyspaces   `protobuf:"bytes,2,opt,name=desc_keyspaces,json=descKeyspaces" json:"desc_keyspaces,omitempty"`
	DescCluster     *DescribeRequest_DescCluster     `protobuf:"bytes,3,opt,name=desc_cluster,json=descCluster" json:"desc_cluster,omitempty"`
	DescClients     *DescribeRequest_DescClients     `protobuf:"bytes,4,opt,name=desc_clients,json=descClients" json:"desc_clients,omitempty"`
}

func (m *DescribeRequest) Reset()                    { *m = DescribeRequest{} }
func (m *DescribeRequest) String() string            { return proto.CompactTextString(m) }
func (*DescribeRequest) ProtoMessage()               {}
func (*DescribeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{32} }

func (m *DescribeRequest) GetDescDataCenters() *DescribeRequest_DescDataCenters {
	if m != nil {
		return m.DescDataCenters
	}
	return nil
}

func (m *DescribeRequest) GetDescKeyspaces() *DescribeRequest_DescKeyspaces {
	if m != nil {
		return m.DescKeyspaces
	}
	return nil
}

func (m *DescribeRequest) GetDescCluster() *DescribeRequest_DescCluster {
	if m != nil {
		return m.DescCluster
	}
	return nil
}

func (m *DescribeRequest) GetDescClients() *DescribeRequest_DescClients {
	if m != nil {
		return m.DescClients
	}
	return nil
}

type DescribeRequest_DescDataCenters struct {
}

func (m *DescribeRequest_DescDataCenters) Reset()         { *m = DescribeRequest_DescDataCenters{} }
func (m *DescribeRequest_DescDataCenters) String() string { return proto.CompactTextString(m) }
func (*DescribeRequest_DescDataCenters) ProtoMessage()    {}
func (*DescribeRequest_DescDataCenters) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{32, 0}
}

type DescribeRequest_DescKeyspaces struct {
}

func (m *DescribeRequest_DescKeyspaces) Reset()         { *m = DescribeRequest_DescKeyspaces{} }
func (m *DescribeRequest_DescKeyspaces) String() string { return proto.CompactTextString(m) }
func (*DescribeRequest_DescKeyspaces) ProtoMessage()    {}
func (*DescribeRequest_DescKeyspaces) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{32, 1}
}

type DescribeRequest_DescCluster struct {
	Keyspace   string `protobuf:"bytes,1,opt,name=keyspace" json:"keyspace,omitempty"`
	DataCenter string `protobuf:"bytes,2,opt,name=data_center,json=dataCenter" json:"data_center,omitempty"`
}

func (m *DescribeRequest_DescCluster) Reset()                    { *m = DescribeRequest_DescCluster{} }
func (m *DescribeRequest_DescCluster) String() string            { return proto.CompactTextString(m) }
func (*DescribeRequest_DescCluster) ProtoMessage()               {}
func (*DescribeRequest_DescCluster) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{32, 2} }

func (m *DescribeRequest_DescCluster) GetKeyspace() string {
	if m != nil {
		return m.Keyspace
	}
	return ""
}

func (m *DescribeRequest_DescCluster) GetDataCenter() string {
	if m != nil {
		return m.DataCenter
	}
	return ""
}

type DescribeRequest_DescClients struct {
}

func (m *DescribeRequest_DescClients) Reset()                    { *m = DescribeRequest_DescClients{} }
func (m *DescribeRequest_DescClients) String() string            { return proto.CompactTextString(m) }
func (*DescribeRequest_DescClients) ProtoMessage()               {}
func (*DescribeRequest_DescClients) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{32, 3} }

type DescribeResponse struct {
	DescDataCenters *DescribeResponse_DescDataCenters `protobuf:"bytes,1,opt,name=desc_data_centers,json=descDataCenters" json:"desc_data_centers,omitempty"`
	DescKeyspaces   *DescribeResponse_DescKeyspaces   `protobuf:"bytes,2,opt,name=desc_keyspaces,json=descKeyspaces" json:"desc_keyspaces,omitempty"`
	DescCluster     *DescribeResponse_DescCluster     `protobuf:"bytes,3,opt,name=desc_cluster,json=descCluster" json:"desc_cluster,omitempty"`
	ClientCount     uint32                            `protobuf:"varint,4,opt,name=client_count,json=clientCount" json:"client_count,omitempty"`
}

func (m *DescribeResponse) Reset()                    { *m = DescribeResponse{} }
func (m *DescribeResponse) String() string            { return proto.CompactTextString(m) }
func (*DescribeResponse) ProtoMessage()               {}
func (*DescribeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{33} }

func (m *DescribeResponse) GetDescDataCenters() *DescribeResponse_DescDataCenters {
	if m != nil {
		return m.DescDataCenters
	}
	return nil
}

func (m *DescribeResponse) GetDescKeyspaces() *DescribeResponse_DescKeyspaces {
	if m != nil {
		return m.DescKeyspaces
	}
	return nil
}

func (m *DescribeResponse) GetDescCluster() *DescribeResponse_DescCluster {
	if m != nil {
		return m.DescCluster
	}
	return nil
}

func (m *DescribeResponse) GetClientCount() uint32 {
	if m != nil {
		return m.ClientCount
	}
	return 0
}

type DescribeResponse_DescDataCenters struct {
	DataCenters []*DescribeResponse_DescDataCenters_DataCenter `protobuf:"bytes,1,rep,name=data_centers,json=dataCenters" json:"data_centers,omitempty"`
}

func (m *DescribeResponse_DescDataCenters) Reset()         { *m = DescribeResponse_DescDataCenters{} }
func (m *DescribeResponse_DescDataCenters) String() string { return proto.CompactTextString(m) }
func (*DescribeResponse_DescDataCenters) ProtoMessage()    {}
func (*DescribeResponse_DescDataCenters) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{33, 0}
}

func (m *DescribeResponse_DescDataCenters) GetDataCenters() []*DescribeResponse_DescDataCenters_DataCenter {
	if m != nil {
		return m.DataCenters
	}
	return nil
}

type DescribeResponse_DescDataCenters_DataCenter struct {
	DataCenter     string           `protobuf:"bytes,1,opt,name=data_center,json=dataCenter" json:"data_center,omitempty"`
	StoreResources []*StoreResource `protobuf:"bytes,2,rep,name=store_resources,json=storeResources" json:"store_resources,omitempty"`
	ClientCount    uint32           `protobuf:"varint,3,opt,name=client_count,json=clientCount" json:"client_count,omitempty"`
}

func (m *DescribeResponse_DescDataCenters_DataCenter) Reset() {
	*m = DescribeResponse_DescDataCenters_DataCenter{}
}
func (m *DescribeResponse_DescDataCenters_DataCenter) String() string {
	return proto.CompactTextString(m)
}
func (*DescribeResponse_DescDataCenters_DataCenter) ProtoMessage() {}
func (*DescribeResponse_DescDataCenters_DataCenter) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{33, 0, 0}
}

func (m *DescribeResponse_DescDataCenters_DataCenter) GetDataCenter() string {
	if m != nil {
		return m.DataCenter
	}
	return ""
}

func (m *DescribeResponse_DescDataCenters_DataCenter) GetStoreResources() []*StoreResource {
	if m != nil {
		return m.StoreResources
	}
	return nil
}

func (m *DescribeResponse_DescDataCenters_DataCenter) GetClientCount() uint32 {
	if m != nil {
		return m.ClientCount
	}
	return 0
}

type DescribeResponse_DescKeyspaces struct {
	Keyspaces []*DescribeResponse_DescKeyspaces_Keyspace `protobuf:"bytes,1,rep,name=keyspaces" json:"keyspaces,omitempty"`
}

func (m *DescribeResponse_DescKeyspaces) Reset()         { *m = DescribeResponse_DescKeyspaces{} }
func (m *DescribeResponse_DescKeyspaces) String() string { return proto.CompactTextString(m) }
func (*DescribeResponse_DescKeyspaces) ProtoMessage()    {}
func (*DescribeResponse_DescKeyspaces) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{33, 1}
}

func (m *DescribeResponse_DescKeyspaces) GetKeyspaces() []*DescribeResponse_DescKeyspaces_Keyspace {
	if m != nil {
		return m.Keyspaces
	}
	return nil
}

type DescribeResponse_DescKeyspaces_Keyspace struct {
	Keyspace    string     `protobuf:"bytes,1,opt,name=keyspace" json:"keyspace,omitempty"`
	Clusters    []*Cluster `protobuf:"bytes,2,rep,name=clusters" json:"clusters,omitempty"`
	ClientCount uint32     `protobuf:"varint,3,opt,name=client_count,json=clientCount" json:"client_count,omitempty"`
}

func (m *DescribeResponse_DescKeyspaces_Keyspace) Reset() {
	*m = DescribeResponse_DescKeyspaces_Keyspace{}
}
func (m *DescribeResponse_DescKeyspaces_Keyspace) String() string { return proto.CompactTextString(m) }
func (*DescribeResponse_DescKeyspaces_Keyspace) ProtoMessage()    {}
func (*DescribeResponse_DescKeyspaces_Keyspace) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{33, 1, 0}
}

func (m *DescribeResponse_DescKeyspaces_Keyspace) GetKeyspace() string {
	if m != nil {
		return m.Keyspace
	}
	return ""
}

func (m *DescribeResponse_DescKeyspaces_Keyspace) GetClusters() []*Cluster {
	if m != nil {
		return m.Clusters
	}
	return nil
}

func (m *DescribeResponse_DescKeyspaces_Keyspace) GetClientCount() uint32 {
	if m != nil {
		return m.ClientCount
	}
	return 0
}

type DescribeResponse_DescCluster struct {
	Cluster     *Cluster `protobuf:"bytes,1,opt,name=cluster" json:"cluster,omitempty"`
	ClientCount uint32   `protobuf:"varint,3,opt,name=client_count,json=clientCount" json:"client_count,omitempty"`
}

func (m *DescribeResponse_DescCluster) Reset()         { *m = DescribeResponse_DescCluster{} }
func (m *DescribeResponse_DescCluster) String() string { return proto.CompactTextString(m) }
func (*DescribeResponse_DescCluster) ProtoMessage()    {}
func (*DescribeResponse_DescCluster) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{33, 2}
}

func (m *DescribeResponse_DescCluster) GetCluster() *Cluster {
	if m != nil {
		return m.Cluster
	}
	return nil
}

func (m *DescribeResponse_DescCluster) GetClientCount() uint32 {
	if m != nil {
		return m.ClientCount
	}
	return 0
}

type CreateClusterRequest struct {
	DataCenter        string   `protobuf:"bytes,1,opt,name=data_center,json=dataCenter" json:"data_center,omitempty"`
	Keyspace          string   `protobuf:"bytes,2,opt,name=keyspace" json:"keyspace,omitempty"`
	ClusterSize       uint32   `protobuf:"varint,3,opt,name=cluster_size,json=clusterSize" json:"cluster_size,omitempty"`
	ReplicationFactor uint32   `protobuf:"varint,4,opt,name=replication_factor,json=replicationFactor" json:"replication_factor,omitempty"`
	TotalDiskSizeGb   uint32   `protobuf:"varint,5,opt,name=total_disk_size_gb,json=totalDiskSizeGb" json:"total_disk_size_gb,omitempty"`
	Tags              []string `protobuf:"bytes,6,rep,name=tags" json:"tags,omitempty"`
}

func (m *CreateClusterRequest) Reset()                    { *m = CreateClusterRequest{} }
func (m *CreateClusterRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateClusterRequest) ProtoMessage()               {}
func (*CreateClusterRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{34} }

func (m *CreateClusterRequest) GetDataCenter() string {
	if m != nil {
		return m.DataCenter
	}
	return ""
}

func (m *CreateClusterRequest) GetKeyspace() string {
	if m != nil {
		return m.Keyspace
	}
	return ""
}

func (m *CreateClusterRequest) GetClusterSize() uint32 {
	if m != nil {
		return m.ClusterSize
	}
	return 0
}

func (m *CreateClusterRequest) GetReplicationFactor() uint32 {
	if m != nil {
		return m.ReplicationFactor
	}
	return 0
}

func (m *CreateClusterRequest) GetTotalDiskSizeGb() uint32 {
	if m != nil {
		return m.TotalDiskSizeGb
	}
	return 0
}

func (m *CreateClusterRequest) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type CreateClusterResponse struct {
	Error   string   `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	Cluster *Cluster `protobuf:"bytes,2,opt,name=cluster" json:"cluster,omitempty"`
}

func (m *CreateClusterResponse) Reset()                    { *m = CreateClusterResponse{} }
func (m *CreateClusterResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateClusterResponse) ProtoMessage()               {}
func (*CreateClusterResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{35} }

func (m *CreateClusterResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *CreateClusterResponse) GetCluster() *Cluster {
	if m != nil {
		return m.Cluster
	}
	return nil
}

type DeleteClusterRequest struct {
	DataCenter string `protobuf:"bytes,1,opt,name=data_center,json=dataCenter" json:"data_center,omitempty"`
	Keyspace   string `protobuf:"bytes,2,opt,name=keyspace" json:"keyspace,omitempty"`
}

func (m *DeleteClusterRequest) Reset()                    { *m = DeleteClusterRequest{} }
func (m *DeleteClusterRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteClusterRequest) ProtoMessage()               {}
func (*DeleteClusterRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{36} }

func (m *DeleteClusterRequest) GetDataCenter() string {
	if m != nil {
		return m.DataCenter
	}
	return ""
}

func (m *DeleteClusterRequest) GetKeyspace() string {
	if m != nil {
		return m.Keyspace
	}
	return ""
}

type DeleteClusterResponse struct {
	Error string `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
}

func (m *DeleteClusterResponse) Reset()                    { *m = DeleteClusterResponse{} }
func (m *DeleteClusterResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteClusterResponse) ProtoMessage()               {}
func (*DeleteClusterResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{37} }

func (m *DeleteClusterResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type CreateShardRequest struct {
	Keyspace          string `protobuf:"bytes,1,opt,name=keyspace" json:"keyspace,omitempty"`
	ShardId           uint32 `protobuf:"varint,2,opt,name=shard_id,json=shardId" json:"shard_id,omitempty"`
	ClusterSize       uint32 `protobuf:"varint,3,opt,name=cluster_size,json=clusterSize" json:"cluster_size,omitempty"`
	ReplicationFactor uint32 `protobuf:"varint,4,opt,name=replication_factor,json=replicationFactor" json:"replication_factor,omitempty"`
	ShardDiskSizeGb   uint32 `protobuf:"varint,5,opt,name=shard_disk_size_gb,json=shardDiskSizeGb" json:"shard_disk_size_gb,omitempty"`
}

func (m *CreateShardRequest) Reset()                    { *m = CreateShardRequest{} }
func (m *CreateShardRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateShardRequest) ProtoMessage()               {}
func (*CreateShardRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{38} }

func (m *CreateShardRequest) GetKeyspace() string {
	if m != nil {
		return m.Keyspace
	}
	return ""
}

func (m *CreateShardRequest) GetShardId() uint32 {
	if m != nil {
		return m.ShardId
	}
	return 0
}

func (m *CreateShardRequest) GetClusterSize() uint32 {
	if m != nil {
		return m.ClusterSize
	}
	return 0
}

func (m *CreateShardRequest) GetReplicationFactor() uint32 {
	if m != nil {
		return m.ReplicationFactor
	}
	return 0
}

func (m *CreateShardRequest) GetShardDiskSizeGb() uint32 {
	if m != nil {
		return m.ShardDiskSizeGb
	}
	return 0
}

type CreateShardResponse struct {
	Error string `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
}

func (m *CreateShardResponse) Reset()                    { *m = CreateShardResponse{} }
func (m *CreateShardResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateShardResponse) ProtoMessage()               {}
func (*CreateShardResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{39} }

func (m *CreateShardResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type DeleteKeyspaceRequest struct {
	Keyspace string `protobuf:"bytes,1,opt,name=keyspace" json:"keyspace,omitempty"`
}

func (m *DeleteKeyspaceRequest) Reset()                    { *m = DeleteKeyspaceRequest{} }
func (m *DeleteKeyspaceRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteKeyspaceRequest) ProtoMessage()               {}
func (*DeleteKeyspaceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{40} }

func (m *DeleteKeyspaceRequest) GetKeyspace() string {
	if m != nil {
		return m.Keyspace
	}
	return ""
}

type DeleteKeyspaceResponse struct {
	Error string `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
}

func (m *DeleteKeyspaceResponse) Reset()                    { *m = DeleteKeyspaceResponse{} }
func (m *DeleteKeyspaceResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteKeyspaceResponse) ProtoMessage()               {}
func (*DeleteKeyspaceResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{41} }

func (m *DeleteKeyspaceResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type ResizeRequest struct {
	DataCenter  string `protobuf:"bytes,1,opt,name=data_center,json=dataCenter" json:"data_center,omitempty"`
	Keyspace    string `protobuf:"bytes,2,opt,name=keyspace" json:"keyspace,omitempty"`
	ClusterSize uint32 `protobuf:"varint,3,opt,name=cluster_size,json=clusterSize" json:"cluster_size,omitempty"`
}

func (m *ResizeRequest) Reset()                    { *m = ResizeRequest{} }
func (m *ResizeRequest) String() string            { return proto.CompactTextString(m) }
func (*ResizeRequest) ProtoMessage()               {}
func (*ResizeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{42} }

func (m *ResizeRequest) GetDataCenter() string {
	if m != nil {
		return m.DataCenter
	}
	return ""
}

func (m *ResizeRequest) GetKeyspace() string {
	if m != nil {
		return m.Keyspace
	}
	return ""
}

func (m *ResizeRequest) GetClusterSize() uint32 {
	if m != nil {
		return m.ClusterSize
	}
	return 0
}

type ResizeProgress struct {
	Error                     string `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	Progress                  string `protobuf:"bytes,2,opt,name=progress" json:"progress,omitempty"`
	HasNotifiedClientsToStart bool   `protobuf:"varint,3,opt,name=hasNotifiedClientsToStart" json:"hasNotifiedClientsToStart,omitempty"`
	HasNotifiedStoresToStart  bool   `protobuf:"varint,4,opt,name=hasNotifiedStoresToStart" json:"hasNotifiedStoresToStart,omitempty"`
	AreStoresSplit            bool   `protobuf:"varint,5,opt,name=areStoresSplit" json:"areStoresSplit,omitempty"`
	AreStoresReplicated       bool   `protobuf:"varint,6,opt,name=areStoresReplicated" json:"areStoresReplicated,omitempty"`
	AreStoresCaughtUp         bool   `protobuf:"varint,7,opt,name=areStoresCaughtUp" json:"areStoresCaughtUp,omitempty"`
	HasNotifiedClientsToStop  bool   `protobuf:"varint,8,opt,name=hasNotifiedClientsToStop" json:"hasNotifiedClientsToStop,omitempty"`
	HasNotifiedStoresToStop   bool   `protobuf:"varint,9,opt,name=hasNotifiedStoresToStop" json:"hasNotifiedStoresToStop,omitempty"`
}

func (m *ResizeProgress) Reset()                    { *m = ResizeProgress{} }
func (m *ResizeProgress) String() string            { return proto.CompactTextString(m) }
func (*ResizeProgress) ProtoMessage()               {}
func (*ResizeProgress) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{43} }

func (m *ResizeProgress) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *ResizeProgress) GetProgress() string {
	if m != nil {
		return m.Progress
	}
	return ""
}

func (m *ResizeProgress) GetHasNotifiedClientsToStart() bool {
	if m != nil {
		return m.HasNotifiedClientsToStart
	}
	return false
}

func (m *ResizeProgress) GetHasNotifiedStoresToStart() bool {
	if m != nil {
		return m.HasNotifiedStoresToStart
	}
	return false
}

func (m *ResizeProgress) GetAreStoresSplit() bool {
	if m != nil {
		return m.AreStoresSplit
	}
	return false
}

func (m *ResizeProgress) GetAreStoresReplicated() bool {
	if m != nil {
		return m.AreStoresReplicated
	}
	return false
}

func (m *ResizeProgress) GetAreStoresCaughtUp() bool {
	if m != nil {
		return m.AreStoresCaughtUp
	}
	return false
}

func (m *ResizeProgress) GetHasNotifiedClientsToStop() bool {
	if m != nil {
		return m.HasNotifiedClientsToStop
	}
	return false
}

func (m *ResizeProgress) GetHasNotifiedStoresToStop() bool {
	if m != nil {
		return m.HasNotifiedStoresToStop
	}
	return false
}

func init() {
	proto.RegisterType((*BalanceRequest)(nil), "pb.BalanceRequest")
	proto.RegisterType((*StoreMessage)(nil), "pb.StoreMessage")
	proto.RegisterType((*ClientMessage)(nil), "pb.ClientMessage")
	proto.RegisterType((*ClientMessage_StoreResourceUpdate)(nil), "pb.ClientMessage.StoreResourceUpdate")
	proto.RegisterType((*ClientMessage_Resize)(nil), "pb.ClientMessage.Resize")
	proto.RegisterType((*Cluster)(nil), "pb.Cluster")
	proto.RegisterType((*ClusterNode)(nil), "pb.ClusterNode")
	proto.RegisterType((*StoreResource)(nil), "pb.StoreResource")
	proto.RegisterType((*StoreStatusInCluster)(nil), "pb.StoreStatusInCluster")
	proto.RegisterType((*ShardStatus)(nil), "pb.ShardStatus")
	proto.RegisterType((*StoreHeartbeat)(nil), "pb.StoreHeartbeat")
	proto.RegisterType((*ClientHeartbeat)(nil), "pb.ClientHeartbeat")
	proto.RegisterType((*Empty)(nil), "pb.Empty")
	proto.RegisterType((*Requests)(nil), "pb.Requests")
	proto.RegisterType((*Responses)(nil), "pb.Responses")
	proto.RegisterType((*Request)(nil), "pb.Request")
	proto.RegisterType((*PutRequest)(nil), "pb.PutRequest")
	proto.RegisterType((*PutResponse)(nil), "pb.PutResponse")
	proto.RegisterType((*DeleteRequest)(nil), "pb.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "pb.DeleteResponse")
	proto.RegisterType((*GetRequest)(nil), "pb.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "pb.GetResponse")
	proto.RegisterType((*GetByPrefixRequest)(nil), "pb.GetByPrefixRequest")
	proto.RegisterType((*GetByPrefixResponse)(nil), "pb.GetByPrefixResponse")
	proto.RegisterType((*Response)(nil), "pb.Response")
	proto.RegisterType((*KeyValue)(nil), "pb.KeyValue")
	proto.RegisterType((*CopyDoneMessge)(nil), "pb.CopyDoneMessge")
	proto.RegisterType((*BootstrapCopyRequest)(nil), "pb.BootstrapCopyRequest")
	proto.RegisterType((*BootstrapCopyResponse)(nil), "pb.BootstrapCopyResponse")
	proto.RegisterType((*BootstrapCopyResponse_BinlogTailProgress)(nil), "pb.BootstrapCopyResponse.BinlogTailProgress")
	proto.RegisterType((*PullUpdateRequest)(nil), "pb.PullUpdateRequest")
	proto.RegisterType((*PullUpdateResponse)(nil), "pb.PullUpdateResponse")
	proto.RegisterType((*UpdateEntry)(nil), "pb.UpdateEntry")
	proto.RegisterType((*CheckBinlogRequest)(nil), "pb.CheckBinlogRequest")
	proto.RegisterType((*CheckBinlogResponse)(nil), "pb.CheckBinlogResponse")
	proto.RegisterType((*DescribeRequest)(nil), "pb.DescribeRequest")
	proto.RegisterType((*DescribeRequest_DescDataCenters)(nil), "pb.DescribeRequest.DescDataCenters")
	proto.RegisterType((*DescribeRequest_DescKeyspaces)(nil), "pb.DescribeRequest.DescKeyspaces")
	proto.RegisterType((*DescribeRequest_DescCluster)(nil), "pb.DescribeRequest.DescCluster")
	proto.RegisterType((*DescribeRequest_DescClients)(nil), "pb.DescribeRequest.DescClients")
	proto.RegisterType((*DescribeResponse)(nil), "pb.DescribeResponse")
	proto.RegisterType((*DescribeResponse_DescDataCenters)(nil), "pb.DescribeResponse.DescDataCenters")
	proto.RegisterType((*DescribeResponse_DescDataCenters_DataCenter)(nil), "pb.DescribeResponse.DescDataCenters.DataCenter")
	proto.RegisterType((*DescribeResponse_DescKeyspaces)(nil), "pb.DescribeResponse.DescKeyspaces")
	proto.RegisterType((*DescribeResponse_DescKeyspaces_Keyspace)(nil), "pb.DescribeResponse.DescKeyspaces.Keyspace")
	proto.RegisterType((*DescribeResponse_DescCluster)(nil), "pb.DescribeResponse.DescCluster")
	proto.RegisterType((*CreateClusterRequest)(nil), "pb.CreateClusterRequest")
	proto.RegisterType((*CreateClusterResponse)(nil), "pb.CreateClusterResponse")
	proto.RegisterType((*DeleteClusterRequest)(nil), "pb.DeleteClusterRequest")
	proto.RegisterType((*DeleteClusterResponse)(nil), "pb.DeleteClusterResponse")
	proto.RegisterType((*CreateShardRequest)(nil), "pb.CreateShardRequest")
	proto.RegisterType((*CreateShardResponse)(nil), "pb.CreateShardResponse")
	proto.RegisterType((*DeleteKeyspaceRequest)(nil), "pb.DeleteKeyspaceRequest")
	proto.RegisterType((*DeleteKeyspaceResponse)(nil), "pb.DeleteKeyspaceResponse")
	proto.RegisterType((*ResizeRequest)(nil), "pb.ResizeRequest")
	proto.RegisterType((*ResizeProgress)(nil), "pb.ResizeProgress")
	proto.RegisterEnum("pb.ShardStatus_Status", ShardStatus_Status_name, ShardStatus_Status_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for VastoMaster service

type VastoMasterClient interface {
	RegisterStore(ctx context.Context, opts ...grpc.CallOption) (VastoMaster_RegisterStoreClient, error)
	RegisterClient(ctx context.Context, opts ...grpc.CallOption) (VastoMaster_RegisterClientClient, error)
	Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*DescribeResponse, error)
	CreateCluster(ctx context.Context, in *CreateClusterRequest, opts ...grpc.CallOption) (*CreateClusterResponse, error)
	DeleteCluster(ctx context.Context, in *DeleteClusterRequest, opts ...grpc.CallOption) (*DeleteClusterResponse, error)
	ResizeCluster(ctx context.Context, in *ResizeRequest, opts ...grpc.CallOption) (VastoMaster_ResizeClusterClient, error)
}

type vastoMasterClient struct {
	cc *grpc.ClientConn
}

func NewVastoMasterClient(cc *grpc.ClientConn) VastoMasterClient {
	return &vastoMasterClient{cc}
}

func (c *vastoMasterClient) RegisterStore(ctx context.Context, opts ...grpc.CallOption) (VastoMaster_RegisterStoreClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_VastoMaster_serviceDesc.Streams[0], c.cc, "/pb.VastoMaster/RegisterStore", opts...)
	if err != nil {
		return nil, err
	}
	x := &vastoMasterRegisterStoreClient{stream}
	return x, nil
}

type VastoMaster_RegisterStoreClient interface {
	Send(*StoreHeartbeat) error
	Recv() (*StoreMessage, error)
	grpc.ClientStream
}

type vastoMasterRegisterStoreClient struct {
	grpc.ClientStream
}

func (x *vastoMasterRegisterStoreClient) Send(m *StoreHeartbeat) error {
	return x.ClientStream.SendMsg(m)
}

func (x *vastoMasterRegisterStoreClient) Recv() (*StoreMessage, error) {
	m := new(StoreMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *vastoMasterClient) RegisterClient(ctx context.Context, opts ...grpc.CallOption) (VastoMaster_RegisterClientClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_VastoMaster_serviceDesc.Streams[1], c.cc, "/pb.VastoMaster/RegisterClient", opts...)
	if err != nil {
		return nil, err
	}
	x := &vastoMasterRegisterClientClient{stream}
	return x, nil
}

type VastoMaster_RegisterClientClient interface {
	Send(*ClientHeartbeat) error
	Recv() (*ClientMessage, error)
	grpc.ClientStream
}

type vastoMasterRegisterClientClient struct {
	grpc.ClientStream
}

func (x *vastoMasterRegisterClientClient) Send(m *ClientHeartbeat) error {
	return x.ClientStream.SendMsg(m)
}

func (x *vastoMasterRegisterClientClient) Recv() (*ClientMessage, error) {
	m := new(ClientMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *vastoMasterClient) Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*DescribeResponse, error) {
	out := new(DescribeResponse)
	err := grpc.Invoke(ctx, "/pb.VastoMaster/Describe", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vastoMasterClient) CreateCluster(ctx context.Context, in *CreateClusterRequest, opts ...grpc.CallOption) (*CreateClusterResponse, error) {
	out := new(CreateClusterResponse)
	err := grpc.Invoke(ctx, "/pb.VastoMaster/CreateCluster", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vastoMasterClient) DeleteCluster(ctx context.Context, in *DeleteClusterRequest, opts ...grpc.CallOption) (*DeleteClusterResponse, error) {
	out := new(DeleteClusterResponse)
	err := grpc.Invoke(ctx, "/pb.VastoMaster/DeleteCluster", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vastoMasterClient) ResizeCluster(ctx context.Context, in *ResizeRequest, opts ...grpc.CallOption) (VastoMaster_ResizeClusterClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_VastoMaster_serviceDesc.Streams[2], c.cc, "/pb.VastoMaster/ResizeCluster", opts...)
	if err != nil {
		return nil, err
	}
	x := &vastoMasterResizeClusterClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type VastoMaster_ResizeClusterClient interface {
	Recv() (*ResizeProgress, error)
	grpc.ClientStream
}

type vastoMasterResizeClusterClient struct {
	grpc.ClientStream
}

func (x *vastoMasterResizeClusterClient) Recv() (*ResizeProgress, error) {
	m := new(ResizeProgress)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for VastoMaster service

type VastoMasterServer interface {
	RegisterStore(VastoMaster_RegisterStoreServer) error
	RegisterClient(VastoMaster_RegisterClientServer) error
	Describe(context.Context, *DescribeRequest) (*DescribeResponse, error)
	CreateCluster(context.Context, *CreateClusterRequest) (*CreateClusterResponse, error)
	DeleteCluster(context.Context, *DeleteClusterRequest) (*DeleteClusterResponse, error)
	ResizeCluster(*ResizeRequest, VastoMaster_ResizeClusterServer) error
}

func RegisterVastoMasterServer(s *grpc.Server, srv VastoMasterServer) {
	s.RegisterService(&_VastoMaster_serviceDesc, srv)
}

func _VastoMaster_RegisterStore_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(VastoMasterServer).RegisterStore(&vastoMasterRegisterStoreServer{stream})
}

type VastoMaster_RegisterStoreServer interface {
	Send(*StoreMessage) error
	Recv() (*StoreHeartbeat, error)
	grpc.ServerStream
}

type vastoMasterRegisterStoreServer struct {
	grpc.ServerStream
}

func (x *vastoMasterRegisterStoreServer) Send(m *StoreMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *vastoMasterRegisterStoreServer) Recv() (*StoreHeartbeat, error) {
	m := new(StoreHeartbeat)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _VastoMaster_RegisterClient_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(VastoMasterServer).RegisterClient(&vastoMasterRegisterClientServer{stream})
}

type VastoMaster_RegisterClientServer interface {
	Send(*ClientMessage) error
	Recv() (*ClientHeartbeat, error)
	grpc.ServerStream
}

type vastoMasterRegisterClientServer struct {
	grpc.ServerStream
}

func (x *vastoMasterRegisterClientServer) Send(m *ClientMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *vastoMasterRegisterClientServer) Recv() (*ClientHeartbeat, error) {
	m := new(ClientHeartbeat)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _VastoMaster_Describe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VastoMasterServer).Describe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.VastoMaster/Describe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VastoMasterServer).Describe(ctx, req.(*DescribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VastoMaster_CreateCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VastoMasterServer).CreateCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.VastoMaster/CreateCluster",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VastoMasterServer).CreateCluster(ctx, req.(*CreateClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VastoMaster_DeleteCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VastoMasterServer).DeleteCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.VastoMaster/DeleteCluster",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VastoMasterServer).DeleteCluster(ctx, req.(*DeleteClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VastoMaster_ResizeCluster_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ResizeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VastoMasterServer).ResizeCluster(m, &vastoMasterResizeClusterServer{stream})
}

type VastoMaster_ResizeClusterServer interface {
	Send(*ResizeProgress) error
	grpc.ServerStream
}

type vastoMasterResizeClusterServer struct {
	grpc.ServerStream
}

func (x *vastoMasterResizeClusterServer) Send(m *ResizeProgress) error {
	return x.ServerStream.SendMsg(m)
}

var _VastoMaster_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.VastoMaster",
	HandlerType: (*VastoMasterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Describe",
			Handler:    _VastoMaster_Describe_Handler,
		},
		{
			MethodName: "CreateCluster",
			Handler:    _VastoMaster_CreateCluster_Handler,
		},
		{
			MethodName: "DeleteCluster",
			Handler:    _VastoMaster_DeleteCluster_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RegisterStore",
			Handler:       _VastoMaster_RegisterStore_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "RegisterClient",
			Handler:       _VastoMaster_RegisterClient_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "ResizeCluster",
			Handler:       _VastoMaster_ResizeCluster_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "vasto.proto",
}

// Client API for VastoStore service

type VastoStoreClient interface {
	BootstrapCopy(ctx context.Context, in *BootstrapCopyRequest, opts ...grpc.CallOption) (VastoStore_BootstrapCopyClient, error)
	TailBinlog(ctx context.Context, in *PullUpdateRequest, opts ...grpc.CallOption) (VastoStore_TailBinlogClient, error)
	CheckBinlog(ctx context.Context, in *CheckBinlogRequest, opts ...grpc.CallOption) (*CheckBinlogResponse, error)
	CreateShard(ctx context.Context, in *CreateShardRequest, opts ...grpc.CallOption) (*CreateShardResponse, error)
	DeleteKeyspace(ctx context.Context, in *DeleteKeyspaceRequest, opts ...grpc.CallOption) (*DeleteKeyspaceResponse, error)
}

type vastoStoreClient struct {
	cc *grpc.ClientConn
}

func NewVastoStoreClient(cc *grpc.ClientConn) VastoStoreClient {
	return &vastoStoreClient{cc}
}

func (c *vastoStoreClient) BootstrapCopy(ctx context.Context, in *BootstrapCopyRequest, opts ...grpc.CallOption) (VastoStore_BootstrapCopyClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_VastoStore_serviceDesc.Streams[0], c.cc, "/pb.VastoStore/BootstrapCopy", opts...)
	if err != nil {
		return nil, err
	}
	x := &vastoStoreBootstrapCopyClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type VastoStore_BootstrapCopyClient interface {
	Recv() (*BootstrapCopyResponse, error)
	grpc.ClientStream
}

type vastoStoreBootstrapCopyClient struct {
	grpc.ClientStream
}

func (x *vastoStoreBootstrapCopyClient) Recv() (*BootstrapCopyResponse, error) {
	m := new(BootstrapCopyResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *vastoStoreClient) TailBinlog(ctx context.Context, in *PullUpdateRequest, opts ...grpc.CallOption) (VastoStore_TailBinlogClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_VastoStore_serviceDesc.Streams[1], c.cc, "/pb.VastoStore/TailBinlog", opts...)
	if err != nil {
		return nil, err
	}
	x := &vastoStoreTailBinlogClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type VastoStore_TailBinlogClient interface {
	Recv() (*PullUpdateResponse, error)
	grpc.ClientStream
}

type vastoStoreTailBinlogClient struct {
	grpc.ClientStream
}

func (x *vastoStoreTailBinlogClient) Recv() (*PullUpdateResponse, error) {
	m := new(PullUpdateResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *vastoStoreClient) CheckBinlog(ctx context.Context, in *CheckBinlogRequest, opts ...grpc.CallOption) (*CheckBinlogResponse, error) {
	out := new(CheckBinlogResponse)
	err := grpc.Invoke(ctx, "/pb.VastoStore/CheckBinlog", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vastoStoreClient) CreateShard(ctx context.Context, in *CreateShardRequest, opts ...grpc.CallOption) (*CreateShardResponse, error) {
	out := new(CreateShardResponse)
	err := grpc.Invoke(ctx, "/pb.VastoStore/CreateShard", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vastoStoreClient) DeleteKeyspace(ctx context.Context, in *DeleteKeyspaceRequest, opts ...grpc.CallOption) (*DeleteKeyspaceResponse, error) {
	out := new(DeleteKeyspaceResponse)
	err := grpc.Invoke(ctx, "/pb.VastoStore/DeleteKeyspace", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for VastoStore service

type VastoStoreServer interface {
	BootstrapCopy(*BootstrapCopyRequest, VastoStore_BootstrapCopyServer) error
	TailBinlog(*PullUpdateRequest, VastoStore_TailBinlogServer) error
	CheckBinlog(context.Context, *CheckBinlogRequest) (*CheckBinlogResponse, error)
	CreateShard(context.Context, *CreateShardRequest) (*CreateShardResponse, error)
	DeleteKeyspace(context.Context, *DeleteKeyspaceRequest) (*DeleteKeyspaceResponse, error)
}

func RegisterVastoStoreServer(s *grpc.Server, srv VastoStoreServer) {
	s.RegisterService(&_VastoStore_serviceDesc, srv)
}

func _VastoStore_BootstrapCopy_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BootstrapCopyRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VastoStoreServer).BootstrapCopy(m, &vastoStoreBootstrapCopyServer{stream})
}

type VastoStore_BootstrapCopyServer interface {
	Send(*BootstrapCopyResponse) error
	grpc.ServerStream
}

type vastoStoreBootstrapCopyServer struct {
	grpc.ServerStream
}

func (x *vastoStoreBootstrapCopyServer) Send(m *BootstrapCopyResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _VastoStore_TailBinlog_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PullUpdateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VastoStoreServer).TailBinlog(m, &vastoStoreTailBinlogServer{stream})
}

type VastoStore_TailBinlogServer interface {
	Send(*PullUpdateResponse) error
	grpc.ServerStream
}

type vastoStoreTailBinlogServer struct {
	grpc.ServerStream
}

func (x *vastoStoreTailBinlogServer) Send(m *PullUpdateResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _VastoStore_CheckBinlog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckBinlogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VastoStoreServer).CheckBinlog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.VastoStore/CheckBinlog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VastoStoreServer).CheckBinlog(ctx, req.(*CheckBinlogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VastoStore_CreateShard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateShardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VastoStoreServer).CreateShard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.VastoStore/CreateShard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VastoStoreServer).CreateShard(ctx, req.(*CreateShardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VastoStore_DeleteKeyspace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteKeyspaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VastoStoreServer).DeleteKeyspace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.VastoStore/DeleteKeyspace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VastoStoreServer).DeleteKeyspace(ctx, req.(*DeleteKeyspaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _VastoStore_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.VastoStore",
	HandlerType: (*VastoStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckBinlog",
			Handler:    _VastoStore_CheckBinlog_Handler,
		},
		{
			MethodName: "CreateShard",
			Handler:    _VastoStore_CreateShard_Handler,
		},
		{
			MethodName: "DeleteKeyspace",
			Handler:    _VastoStore_DeleteKeyspace_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "BootstrapCopy",
			Handler:       _VastoStore_BootstrapCopy_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "TailBinlog",
			Handler:       _VastoStore_TailBinlog_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "vasto.proto",
}

func init() { proto.RegisterFile("vasto.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 2410 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xbc, 0x19, 0x4b, 0x6f, 0x1c, 0x49,
	0xd9, 0x3d, 0x63, 0x7b, 0x66, 0xbe, 0x9e, 0x87, 0x5d, 0x76, 0x1c, 0x67, 0x10, 0xc4, 0xa9, 0x25,
	0x90, 0xc7, 0xae, 0x09, 0x5e, 0xa1, 0x8d, 0xbc, 0x88, 0x25, 0x7e, 0x24, 0x31, 0x21, 0xb1, 0xe9,
	0x71, 0x16, 0xad, 0x84, 0xd4, 0xb4, 0xa7, 0xcb, 0xe3, 0xc6, 0xed, 0xee, 0xa6, 0xab, 0x66, 0x37,
	0x03, 0x42, 0x5a, 0x71, 0x46, 0x82, 0x1b, 0x47, 0x0e, 0xc0, 0x95, 0x0b, 0x1c, 0x80, 0x9f, 0x80,
	0x04, 0x3f, 0x63, 0x0f, 0x70, 0xe5, 0x07, 0xa0, 0x7a, 0x75, 0x57, 0xcf, 0xf4, 0x8c, 0x1d, 0x25,
	0xe2, 0xd6, 0xf5, 0xbd, 0xea, 0x7b, 0x57, 0x7d, 0xd5, 0x60, 0x7f, 0xea, 0x51, 0x16, 0x6f, 0x26,
	0x69, 0xcc, 0x62, 0x54, 0x49, 0x4e, 0x30, 0x85, 0xf6, 0x8e, 0x17, 0x7a, 0x51, 0x9f, 0x38, 0xe4,
	0xa7, 0x43, 0x42, 0x19, 0xba, 0x09, 0xb6, 0xef, 0x31, 0xcf, 0xed, 0x93, 0x88, 0x91, 0x74, 0xdd,
	0xda, 0xb0, 0xee, 0x34, 0x1c, 0xe0, 0xa0, 0x5d, 0x01, 0xe1, 0x04, 0x94, 0xc5, 0x29, 0x71, 0x07,
	0x69, 0x3c, 0x4c, 0xd6, 0x2b, 0x92, 0x40, 0x80, 0x9e, 0x70, 0x48, 0x4e, 0xd0, 0x8f, 0x87, 0x11,
	0x5b, 0xaf, 0x6e, 0x58, 0x77, 0x5a, 0x8a, 0x60, 0x97, 0x43, 0x70, 0x1b, 0x9a, 0x3d, 0xbe, 0x7a,
	0x4e, 0x28, 0xf5, 0x06, 0x04, 0xff, 0xb1, 0x0a, 0xad, 0xdd, 0x30, 0x20, 0x11, 0x53, 0x10, 0x74,
	0x1b, 0x6a, 0xfd, 0x70, 0x48, 0xb5, 0x02, 0xf6, 0x96, 0xbd, 0x99, 0x9c, 0x6c, 0xee, 0x4a, 0x90,
	0xa3, 0x71, 0xe8, 0x23, 0xa8, 0x0d, 0x13, 0xdf, 0x63, 0x84, 0x0a, 0x35, 0xec, 0xad, 0xdb, 0x92,
	0xcc, 0x10, 0xb5, 0x29, 0x76, 0x72, 0x08, 0x8d, 0x87, 0x69, 0x9f, 0xbc, 0x14, 0xd4, 0x8e, 0xe6,
	0x42, 0x0f, 0x60, 0x31, 0x25, 0x34, 0xf8, 0x19, 0x11, 0x5a, 0xda, 0x5b, 0xeb, 0x93, 0xfc, 0x8e,
	0xc0, 0x3b, 0x8a, 0xae, 0x3b, 0x84, 0x95, 0x12, 0x89, 0xe8, 0x36, 0x2c, 0x44, 0xb1, 0x4f, 0xe8,
	0xba, 0xb5, 0x51, 0xbd, 0x63, 0x6f, 0x75, 0x0c, 0x75, 0x5f, 0xc4, 0x3e, 0x71, 0x24, 0x16, 0x7d,
	0x09, 0x1a, 0x01, 0x75, 0x7d, 0x12, 0x12, 0x46, 0x84, 0xca, 0x75, 0xa7, 0x1e, 0xd0, 0x3d, 0xb1,
	0x46, 0x5d, 0xa8, 0x9f, 0x93, 0x11, 0x4d, 0xbc, 0xbe, 0x54, 0xa7, 0xe1, 0x64, 0xeb, 0xee, 0x2f,
	0x2d, 0x58, 0x94, 0x9a, 0xa0, 0x07, 0xb0, 0xda, 0x1f, 0xa6, 0x29, 0x89, 0x98, 0xab, 0xfc, 0xe0,
	0x0a, 0x0b, 0x2c, 0xe1, 0x67, 0xa4, 0x70, 0x6a, 0xf3, 0x1e, 0xe7, 0xb8, 0x07, 0xcb, 0x11, 0x79,
	0x35, 0x46, 0x5e, 0x11, 0xe4, 0x1d, 0x8e, 0x30, 0x69, 0x67, 0x28, 0x81, 0xff, 0x54, 0x81, 0x9a,
	0xa2, 0x2d, 0xd0, 0x59, 0x45, 0xba, 0xf1, 0x14, 0xaa, 0x4c, 0xa4, 0x50, 0xe6, 0xad, 0xea, 0x4c,
	0x6f, 0x6d, 0xc1, 0x35, 0xf2, 0x2a, 0x21, 0x7d, 0x46, 0xfc, 0xa2, 0xee, 0xf3, 0x42, 0xf7, 0x15,
	0x8d, 0x34, 0xf5, 0x9f, 0xe6, 0x9d, 0x85, 0xd7, 0xf3, 0xce, 0x62, 0xb9, 0x77, 0xde, 0x03, 0x94,
	0x92, 0x24, 0x0c, 0xfa, 0x1e, 0x0b, 0xe2, 0xc8, 0x3d, 0xf5, 0xfa, 0x2c, 0x4e, 0xd7, 0x6b, 0x82,
	0x78, 0xd9, 0xc0, 0x3c, 0x16, 0x08, 0xfc, 0x73, 0xb0, 0x0d, 0xb3, 0xd0, 0x43, 0x68, 0xcb, 0xc2,
	0x48, 0x55, 0xf2, 0xa8, 0xe4, 0x5e, 0xe6, 0xf6, 0x17, 0xb2, 0xca, 0x69, 0x51, 0x73, 0x89, 0xb6,
	0xa0, 0x49, 0xcf, 0xbc, 0xd4, 0x77, 0x29, 0xf3, 0xd8, 0x50, 0x67, 0xbb, 0xf0, 0x5b, 0x8f, 0xc3,
	0x7b, 0x02, 0xec, 0xd8, 0x34, 0x5f, 0xe0, 0xff, 0x58, 0xd0, 0x2a, 0x08, 0xbd, 0xbc, 0xb4, 0xd7,
	0xa1, 0x16, 0x11, 0xf6, 0x59, 0x9c, 0x9e, 0xab, 0xa0, 0xe9, 0x25, 0xc7, 0x78, 0xbe, 0x9f, 0x12,
	0x4a, 0x55, 0x56, 0xe8, 0x25, 0x7a, 0x07, 0x5a, 0x9e, 0x7f, 0x11, 0x44, 0xae, 0xc6, 0xcf, 0x0b,
	0x7c, 0x53, 0x00, 0x1f, 0x29, 0x22, 0x04, 0xf3, 0xcc, 0x1b, 0xd0, 0xf5, 0xda, 0x46, 0xf5, 0x4e,
	0xc3, 0x11, 0xdf, 0x68, 0x03, 0x9a, 0x7e, 0x40, 0xcf, 0x85, 0xbf, 0xdd, 0xc1, 0xc9, 0x7a, 0x5d,
	0xf6, 0x09, 0x0e, 0xe3, 0xbe, 0x7e, 0x72, 0xc2, 0x23, 0xe3, 0x85, 0x61, 0xdc, 0xf7, 0x78, 0x02,
	0x68, 0xb2, 0x86, 0x8c, 0x4c, 0x86, 0x90, 0xb4, 0xf8, 0x77, 0x15, 0x58, 0x15, 0xd6, 0x4a, 0xeb,
	0x0f, 0x22, 0x9d, 0xa8, 0x6d, 0xa8, 0x04, 0xbe, 0x2a, 0x8e, 0x4a, 0xe0, 0x23, 0x07, 0xda, 0xa6,
	0x2b, 0x45, 0xeb, 0xe0, 0x49, 0x78, 0x3f, 0x0b, 0xc2, 0x98, 0x04, 0xd3, 0xc3, 0x84, 0xee, 0x47,
	0x2c, 0x1d, 0x39, 0x2d, 0x6a, 0xc2, 0xd0, 0x2d, 0x68, 0x16, 0xb2, 0x47, 0xb6, 0x3c, 0xbb, 0x7f,
	0x69, 0xe6, 0xcc, 0x4f, 0xc9, 0x9c, 0xee, 0x0f, 0x00, 0x4d, 0x6e, 0x8b, 0x96, 0xa0, 0x7a, 0x4e,
	0x46, 0xca, 0x18, 0xfe, 0xc9, 0x2b, 0xe9, 0x53, 0x2f, 0x1c, 0x92, 0x69, 0x19, 0x21, 0xb1, 0xdb,
	0x95, 0x87, 0x16, 0xfe, 0x43, 0x05, 0x6c, 0x03, 0xc5, 0x03, 0xa7, 0x2b, 0xd6, 0x8d, 0xbc, 0x0b,
	0x5d, 0xc6, 0x4d, 0x0d, 0x7c, 0xe1, 0x5d, 0x10, 0x74, 0x1d, 0x6a, 0xbc, 0x16, 0xdd, 0xc0, 0x57,
	0x0d, 0x63, 0x91, 0x2f, 0x0f, 0x7c, 0x74, 0x03, 0xea, 0xd2, 0x8d, 0x81, 0xaf, 0xcc, 0xad, 0x89,
	0xf5, 0x81, 0x3f, 0xe1, 0x8d, 0xf9, 0xab, 0x7a, 0x63, 0x61, 0x8a, 0x37, 0xd0, 0x26, 0x2c, 0xaa,
	0xc4, 0xe7, 0x75, 0xd9, 0xde, 0x5a, 0x1b, 0x33, 0x73, 0x53, 0x59, 0xab, 0xa8, 0xf0, 0x36, 0x2c,
	0x2a, 0x23, 0x1b, 0xb0, 0xb0, 0xff, 0xfc, 0xe8, 0xf8, 0x93, 0xa5, 0x39, 0xd4, 0x82, 0xc6, 0xce,
	0xe1, 0xe1, 0x71, 0xef, 0xd8, 0x79, 0x74, 0xb4, 0x64, 0x71, 0x8c, 0xb3, 0xff, 0x68, 0xef, 0x93,
	0xa5, 0x0a, 0xb2, 0xa1, 0xb6, 0xb7, 0xff, 0xfd, 0xfd, 0xe3, 0xfd, 0xbd, 0xa5, 0x2a, 0xfe, 0x05,
	0xb4, 0x45, 0x16, 0x3c, 0x25, 0x5e, 0xca, 0x4e, 0x88, 0xc7, 0xde, 0xa0, 0x6c, 0xbf, 0x09, 0x66,
	0x45, 0x5e, 0xa9, 0x6a, 0x63, 0xe8, 0xc8, 0xf3, 0x27, 0xdf, 0xff, 0xd2, 0xb2, 0x35, 0x7b, 0x71,
	0x65, 0xb2, 0x17, 0x07, 0xd4, 0x1d, 0x46, 0xa7, 0x71, 0x18, 0xc6, 0x9f, 0x89, 0x50, 0xd5, 0x1d,
	0x08, 0xe8, 0x4b, 0x05, 0xc1, 0x35, 0x58, 0xd8, 0xbf, 0x48, 0xd8, 0x08, 0x1f, 0x42, 0x5d, 0xdd,
	0x01, 0xe8, 0xcc, 0xee, 0xfe, 0x75, 0xa8, 0xa7, 0x8a, 0x4e, 0x95, 0x8e, 0x38, 0x9c, 0x15, 0xaf,
	0x93, 0x21, 0xf1, 0x07, 0xd0, 0x70, 0x08, 0x4d, 0xe2, 0x88, 0x97, 0xc8, 0x3d, 0x68, 0xa4, 0x7a,
	0xa1, 0x0e, 0xc9, 0xa6, 0x64, 0x93, 0x40, 0x27, 0x47, 0xe3, 0xbf, 0x58, 0x50, 0xd3, 0xd7, 0x91,
	0x0d, 0xa8, 0x26, 0x43, 0xa6, 0x3c, 0xde, 0xe6, 0x1c, 0x47, 0x43, 0xa6, 0xf7, 0xe2, 0x28, 0x4e,
	0x31, 0x20, 0x4c, 0x39, 0x57, 0x50, 0x3c, 0x21, 0x39, 0xc5, 0x80, 0x30, 0xb4, 0x0d, 0xad, 0x01,
	0x61, 0xee, 0xc9, 0xc8, 0x4d, 0x52, 0x72, 0x1a, 0xbc, 0x52, 0x87, 0xfd, 0x9a, 0xa2, 0xdd, 0x19,
	0x1d, 0x09, 0xb0, 0xe6, 0xb1, 0x07, 0x39, 0x0c, 0xdd, 0x85, 0x45, 0x75, 0x5c, 0xcf, 0xe7, 0x41,
	0x97, 0x07, 0xb6, 0xa6, 0x57, 0x04, 0xf8, 0xb7, 0x16, 0x40, 0xae, 0x1c, 0x6f, 0x99, 0x2a, 0x93,
	0x55, 0xc1, 0xea, 0x25, 0xba, 0x0d, 0xed, 0xc4, 0x4b, 0x59, 0x20, 0x72, 0xff, 0xcc, 0xa3, 0x67,
	0x42, 0xf9, 0x79, 0xa7, 0x95, 0x41, 0x9f, 0x7a, 0xf4, 0x0c, 0xdd, 0x85, 0xc6, 0x39, 0x19, 0xb9,
	0xb2, 0xbe, 0xa5, 0xca, 0xc2, 0x65, 0xcf, 0xc8, 0xe8, 0x63, 0x0e, 0x13, 0x31, 0x11, 0x5f, 0xe8,
	0xcb, 0x00, 0x8c, 0x85, 0x2e, 0x25, 0xfd, 0x38, 0xf2, 0x55, 0xc1, 0x35, 0x18, 0x0b, 0x7b, 0x02,
	0x80, 0xbf, 0x05, 0xb6, 0x50, 0x4c, 0x3a, 0x98, 0xb7, 0xc4, 0xf8, 0x5c, 0x28, 0x55, 0x77, 0x2a,
	0xf1, 0x39, 0x5a, 0xcb, 0xca, 0x4b, 0x66, 0x8f, 0x2e, 0xa3, 0x13, 0x68, 0x15, 0x2c, 0x7d, 0x73,
	0x93, 0x54, 0x03, 0xe3, 0xc6, 0x34, 0x45, 0x03, 0xc3, 0x0f, 0xa1, 0xad, 0xf7, 0x78, 0x4d, 0xed,
	0x1e, 0x02, 0xe4, 0x81, 0x9e, 0xa1, 0x9a, 0xda, 0xb3, 0x92, 0xef, 0xf9, 0x63, 0xb0, 0x05, 0xe7,
	0xeb, 0x6d, 0xf8, 0x1a, 0xf1, 0xc0, 0x9f, 0x5b, 0x80, 0x26, 0x33, 0x6b, 0x86, 0x92, 0x6b, 0xb0,
	0xa8, 0x72, 0x53, 0xea, 0xa9, 0x56, 0x68, 0x15, 0x16, 0xc2, 0xe0, 0x22, 0xd0, 0xb7, 0x68, 0xb9,
	0x40, 0x18, 0x5a, 0xa1, 0x47, 0x99, 0x4b, 0x09, 0x89, 0x5c, 0x6e, 0xdc, 0xbc, 0x60, 0xb2, 0x39,
	0xb0, 0x47, 0x48, 0xf4, 0x8c, 0x8c, 0xf0, 0x4f, 0x60, 0xa5, 0xa0, 0xc1, 0x6b, 0x1a, 0x7b, 0x1f,
	0x20, 0x33, 0x56, 0xdf, 0xd3, 0x8a, 0xd6, 0x36, 0xb4, 0xb5, 0x14, 0xff, 0xcd, 0xe2, 0xbd, 0x43,
	0xed, 0x70, 0xcb, 0xac, 0xd8, 0x4e, 0x56, 0xb1, 0xaa, 0xcc, 0x45, 0xc9, 0xde, 0x32, 0x4b, 0xb6,
	0x93, 0x95, 0xac, 0x26, 0xe1, 0x35, 0xfb, 0x61, 0x79, 0xcd, 0x5e, 0x9f, 0xa8, 0x59, 0xc5, 0x54,
	0x28, 0xda, 0x7b, 0x63, 0x45, 0x8b, 0xcc, 0xa2, 0x55, 0x0c, 0xba, 0x6a, 0xb7, 0xa0, 0xae, 0x4d,
	0x32, 0xcf, 0x57, 0x99, 0x2a, 0xdc, 0xff, 0xf9, 0xf9, 0xda, 0x54, 0xc7, 0x29, 0xee, 0x41, 0x7b,
	0x37, 0x4e, 0x46, 0x7b, 0x71, 0x24, 0x66, 0x98, 0x01, 0xe1, 0x74, 0xa2, 0x8b, 0x0b, 0xde, 0x05,
	0x47, 0x2e, 0xd0, 0x7d, 0x40, 0xfd, 0x38, 0x19, 0xf1, 0xab, 0x46, 0xca, 0x5c, 0x16, 0x5c, 0x10,
	0x37, 0x92, 0x8e, 0xae, 0x3a, 0x1d, 0x8e, 0xe9, 0x71, 0xc4, 0x71, 0x70, 0x41, 0x5e, 0x50, 0xfc,
	0x0c, 0x56, 0x77, 0xe2, 0x98, 0x51, 0x96, 0x7a, 0x09, 0x97, 0xae, 0x93, 0x66, 0x56, 0x2f, 0x9e,
	0x76, 0x3c, 0xe3, 0x7f, 0x5b, 0x70, 0x6d, 0x4c, 0x9a, 0x0a, 0x4f, 0x31, 0xb0, 0xd6, 0xcc, 0xc0,
	0xa2, 0x1f, 0x01, 0x3a, 0x09, 0xa2, 0x30, 0x1e, 0x1c, 0x7b, 0x41, 0x78, 0x94, 0xc6, 0x03, 0x71,
	0xc3, 0x93, 0x71, 0x7b, 0x97, 0x33, 0x95, 0xee, 0xb1, 0xb9, 0x33, 0xc1, 0xe3, 0x94, 0xc8, 0xe9,
	0x3e, 0x06, 0x34, 0x49, 0xc9, 0x8b, 0x84, 0x92, 0xc1, 0x05, 0x89, 0x98, 0x2e, 0x12, 0xb5, 0xe4,
	0xb9, 0x1a, 0x9f, 0x9e, 0x52, 0x95, 0x39, 0xf3, 0x8e, 0x5a, 0xe1, 0xdf, 0x58, 0xb0, 0x7c, 0x34,
	0x0c, 0x43, 0x35, 0xdd, 0xbd, 0x81, 0xdf, 0xcc, 0xcd, 0xab, 0xd3, 0x36, 0x9f, 0x37, 0x37, 0xcf,
	0x2b, 0x74, 0xc1, 0xa8, 0x50, 0xfc, 0x7b, 0x0b, 0x90, 0xa9, 0x52, 0x56, 0x1b, 0x4d, 0x31, 0x6b,
	0x14, 0x0d, 0xb4, 0x39, 0xac, 0xa7, 0xf6, 0xb9, 0x09, 0x62, 0xe9, 0x16, 0x2c, 0x05, 0x0e, 0x3a,
	0x94, 0x1b, 0xde, 0x85, 0x1a, 0x89, 0x58, 0x1a, 0x14, 0xc7, 0x27, 0xb9, 0x91, 0xbc, 0x9d, 0x6a,
	0x3c, 0xfa, 0x0a, 0xd8, 0xf1, 0x90, 0x8b, 0x72, 0xe9, 0x28, 0xea, 0x0b, 0xc5, 0xeb, 0x4e, 0x23,
	0x1e, 0xb2, 0xc3, 0xd3, 0xde, 0x28, 0xea, 0xe3, 0x7f, 0x5a, 0x60, 0x1b, 0x8c, 0x25, 0x5d, 0xbc,
	0x5a, 0xd6, 0xc5, 0x31, 0xb4, 0xe4, 0x00, 0xed, 0xbb, 0x1e, 0xe3, 0x19, 0x2d, 0x3d, 0x62, 0x2b,
	0xe0, 0x23, 0xf6, 0x82, 0x8e, 0x9d, 0x48, 0x0b, 0x63, 0x27, 0x12, 0xaf, 0xb4, 0x7e, 0xda, 0x57,
	0x63, 0x16, 0xff, 0xe4, 0xe1, 0xd2, 0x93, 0xb0, 0x18, 0xa8, 0xcc, 0xc9, 0x58, 0xd5, 0x65, 0xbd,
	0xa4, 0x2e, 0x1b, 0x66, 0x5d, 0x1e, 0x00, 0xda, 0x3d, 0x23, 0xfd, 0x73, 0x99, 0x55, 0x6f, 0x54,
	0x40, 0x9f, 0x5b, 0xb0, 0x52, 0x90, 0xa5, 0x22, 0x68, 0x30, 0x58, 0x85, 0xcc, 0xb9, 0x0b, 0x4b,
	0xc4, 0x4b, 0xc3, 0x80, 0xd0, 0x3c, 0xbc, 0x6a, 0xc6, 0xd6, 0x70, 0x1d, 0xe2, 0xdb, 0xd0, 0x0e,
	0x3d, 0x66, 0x12, 0xca, 0x5c, 0x6b, 0x49, 0xa8, 0x22, 0xc3, 0x7f, 0xae, 0x42, 0x67, 0x8f, 0xd0,
	0x7e, 0x1a, 0x9c, 0x64, 0x49, 0x7d, 0x08, 0xcb, 0x3e, 0xa1, 0x7d, 0xd7, 0xb8, 0x10, 0x52, 0xd5,
	0x6a, 0xdf, 0x91, 0x4d, 0xae, 0x40, 0x2f, 0xd6, 0x7b, 0xd9, 0x4d, 0x91, 0x3a, 0x1d, 0xbf, 0x08,
	0x40, 0x4f, 0xa1, 0x2d, 0x04, 0x6a, 0x8f, 0xe8, 0xea, 0xbe, 0x35, 0x4d, 0xda, 0x33, 0x4d, 0xe8,
	0xb4, 0x7c, 0x73, 0x89, 0x76, 0xa0, 0x29, 0x24, 0xe9, 0x87, 0x1b, 0xd9, 0xb0, 0x6f, 0x4e, 0x93,
	0xa3, 0x1f, 0x73, 0x6c, 0x3f, 0x5f, 0x18, 0x32, 0xf8, 0x15, 0x98, 0xaa, 0xf6, 0x3d, 0x43, 0x86,
	0x20, 0xd3, 0x32, 0xc4, 0xa2, 0xbb, 0x2c, 0xbd, 0x66, 0x18, 0xd9, 0xed, 0xf0, 0x8b, 0x8c, 0xa1,
	0x6b, 0xf7, 0x7b, 0x60, 0x1b, 0x3a, 0xbc, 0xd1, 0x63, 0x46, 0xb7, 0xa5, 0x65, 0x89, 0xed, 0xf1,
	0x5f, 0x17, 0x61, 0x29, 0xd7, 0x55, 0x65, 0xcd, 0xd1, 0xf4, 0xb0, 0x7d, 0xb5, 0x68, 0x9c, 0xea,
	0xa0, 0x97, 0xc6, 0xed, 0x60, 0x4a, 0xdc, 0xf0, 0x54, 0x71, 0x53, 0x03, 0xb7, 0x5b, 0x1a, 0xb8,
	0x8d, 0xa9, 0x82, 0x4a, 0x23, 0x27, 0x86, 0xbe, 0x40, 0x3c, 0xbb, 0x88, 0x57, 0xbf, 0x6c, 0xe8,
	0xe3, 0x30, 0xf1, 0xec, 0xd7, 0xfd, 0xaf, 0x35, 0x11, 0x19, 0xe4, 0x40, 0x73, 0xcc, 0x27, 0xbc,
	0xa3, 0x7d, 0xe3, 0x2a, 0x3e, 0xd9, 0xcc, 0xbf, 0x1d, 0xdb, 0x37, 0xa2, 0xfd, 0x2b, 0x0b, 0x60,
	0xaf, 0xf0, 0x5e, 0x39, 0x7b, 0x7c, 0xda, 0x86, 0x4e, 0x71, 0xbe, 0xd3, 0x73, 0x4d, 0xc9, 0x80,
	0xd7, 0x2e, 0x0c, 0x78, 0x74, 0xc2, 0xec, 0xea, 0xa4, 0xd9, 0xff, 0xb2, 0xc6, 0xb2, 0x0f, 0x1d,
	0x88, 0x8b, 0xa4, 0x0a, 0x9b, 0x95, 0xbf, 0x3e, 0xcc, 0x0e, 0xdb, 0xa6, 0xfe, 0x72, 0x72, 0xee,
	0x6e, 0x2a, 0x6e, 0x2f, 0x32, 0x53, 0x2f, 0x19, 0xda, 0x54, 0x78, 0x0b, 0x43, 0x9b, 0x0e, 0x65,
	0x86, 0xbc, 0x8a, 0x41, 0x3f, 0x2c, 0x16, 0xcf, 0x15, 0xdf, 0x6a, 0x2f, 0x17, 0x8c, 0xbf, 0xb0,
	0x60, 0x75, 0x37, 0x25, 0x1e, 0x23, 0x9a, 0xfb, 0xaa, 0x6f, 0xd2, 0xb3, 0x26, 0xe0, 0xb7, 0xfe,
	0x38, 0xc3, 0xaf, 0x75, 0x2c, 0x66, 0x5e, 0xe8, 0x16, 0xde, 0xaf, 0xe4, 0x19, 0xd7, 0x11, 0x98,
	0xbd, 0xfc, 0x11, 0x4b, 0x3f, 0x7d, 0x2d, 0xe6, 0x4f, 0x5f, 0xf8, 0x18, 0xae, 0x8d, 0xd9, 0xa9,
	0xfa, 0xc4, 0x2a, 0x2c, 0x90, 0x34, 0x8d, 0xb5, 0x89, 0x72, 0x61, 0x7a, 0xb8, 0x32, 0xdd, 0xc3,
	0xb8, 0x07, 0xab, 0xf2, 0xbc, 0x7c, 0x8b, 0xde, 0xc3, 0xef, 0xc1, 0xb5, 0x31, 0xa1, 0xb3, 0x54,
	0xc5, 0xff, 0xb0, 0x00, 0x49, 0xd3, 0xc4, 0x0b, 0xc7, 0x55, 0x8e, 0x60, 0xf3, 0x25, 0xa9, 0x32,
	0xfb, 0x25, 0xe9, 0xad, 0x84, 0x4e, 0x6e, 0x56, 0x16, 0x3a, 0x81, 0xc9, 0x43, 0x87, 0xef, 0xc3,
	0x4a, 0xc1, 0x96, 0x99, 0x96, 0xbf, 0xaf, 0x1d, 0x95, 0x95, 0xe9, 0xe5, 0xb6, 0xe3, 0x4d, 0x58,
	0x1b, 0x67, 0x9a, 0xb9, 0x49, 0x0c, 0x2d, 0xf5, 0x3f, 0xe2, 0xff, 0x53, 0x19, 0xf8, 0xef, 0x55,
	0x68, 0xcb, 0x1d, 0xb3, 0xfb, 0x79, 0x79, 0x8e, 0x76, 0xa1, 0x9e, 0x98, 0xf3, 0x41, 0xc3, 0xc9,
	0xd6, 0xe8, 0xdb, 0x70, 0xe3, 0xcc, 0xa3, 0x2f, 0x62, 0x16, 0x9c, 0x06, 0xc4, 0x57, 0x07, 0xe5,
	0x71, 0x2c, 0x86, 0x1f, 0xf5, 0x22, 0x35, 0x9d, 0x00, 0x6d, 0xc3, 0xba, 0x81, 0x14, 0xed, 0x38,
	0x63, 0x96, 0x37, 0xda, 0xa9, 0x78, 0xf4, 0x35, 0x68, 0x7b, 0x29, 0x91, 0xb0, 0x5e, 0x12, 0xaa,
	0x5b, 0x7a, 0xdd, 0x19, 0x83, 0xa2, 0x07, 0xb0, 0x92, 0x41, 0x1c, 0x95, 0x34, 0xc4, 0x17, 0xd7,
	0xd3, 0xba, 0x53, 0x86, 0x42, 0xef, 0xc2, 0x72, 0x06, 0xde, 0xf5, 0x86, 0x83, 0x33, 0xf6, 0x32,
	0x51, 0xf7, 0xd6, 0x49, 0xc4, 0x98, 0x0d, 0x86, 0x81, 0x71, 0x22, 0x6e, 0xb5, 0x45, 0x1b, 0x0a,
	0x78, 0xf4, 0x10, 0xae, 0x97, 0xda, 0x17, 0x27, 0xe2, 0xf2, 0x5b, 0x77, 0xa6, 0xa1, 0xb7, 0x7e,
	0x5d, 0x05, 0xfb, 0x63, 0x8f, 0xb2, 0xf8, 0xb9, 0x27, 0x5a, 0xf0, 0x87, 0x3c, 0x7b, 0x06, 0x81,
	0x08, 0x2e, 0xa7, 0x43, 0x28, 0x3b, 0xe0, 0xb2, 0xd7, 0xc6, 0xee, 0x52, 0x06, 0xd3, 0xbf, 0xe7,
	0xe6, 0xee, 0x58, 0x0f, 0x2c, 0xf4, 0x1d, 0x9e, 0x08, 0x92, 0x59, 0xea, 0x87, 0x56, 0xf2, 0x9f,
	0x65, 0x39, 0xfb, 0xf2, 0xc4, 0x1f, 0x34, 0xc5, 0xff, 0x01, 0xd4, 0xf5, 0xf9, 0x26, 0x39, 0xc7,
	0x2e, 0x74, 0xdd, 0xd5, 0xb2, 0x23, 0x10, 0xcf, 0xa1, 0xc7, 0xd0, 0x2a, 0x34, 0x4b, 0x24, 0x7f,
	0xd2, 0x95, 0x9c, 0x13, 0xdd, 0x1b, 0x25, 0x18, 0x53, 0x4e, 0xa1, 0x93, 0x49, 0x39, 0x65, 0x1d,
	0x53, 0xca, 0x29, 0x6d, 0x7b, 0x78, 0x0e, 0x6d, 0xeb, 0x1a, 0xd4, 0x72, 0x96, 0xd5, 0x3b, 0x66,
	0x5e, 0x96, 0x5d, 0x94, 0x83, 0x74, 0xdd, 0xe0, 0xb9, 0x07, 0xd6, 0xd6, 0x17, 0x15, 0x00, 0x11,
	0x11, 0xe9, 0xff, 0xa7, 0xd0, 0x2a, 0x0c, 0xd0, 0x52, 0xa5, 0xb2, 0x57, 0x00, 0xa9, 0x52, 0xe9,
	0xb4, 0xcd, 0x05, 0xa3, 0x8f, 0x00, 0xf8, 0x10, 0x2d, 0x87, 0x15, 0x74, 0x4d, 0xbe, 0xba, 0x8c,
	0x4d, 0xc4, 0xdd, 0xb5, 0x71, 0xb0, 0x21, 0xe0, 0xbb, 0x60, 0x1b, 0xe3, 0x0e, 0x12, 0xa4, 0x93,
	0xb3, 0x54, 0xf7, 0xfa, 0x04, 0x3c, 0xf3, 0x0b, 0x97, 0x90, 0x77, 0x4b, 0x25, 0x61, 0xe2, 0x28,
	0x50, 0x12, 0x26, 0xdb, 0x2a, 0x9e, 0xe3, 0x77, 0xda, 0x62, 0x37, 0x44, 0x46, 0x20, 0xc6, 0xda,
	0x6a, 0xb7, 0x5b, 0x86, 0xd2, 0xa2, 0x4e, 0x16, 0xc5, 0x2f, 0xee, 0xf7, 0xff, 0x17, 0x00, 0x00,
	0xff, 0xff, 0x23, 0x45, 0x72, 0x2f, 0xf1, 0x1e, 0x00, 0x00,
}
