// Code generated by protoc-gen-go.
// source: vasto.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	vasto.proto

It has these top-level messages:
	BalanceRequest
	Topology
	Ring
	StoreResource
	Location
	StoreHeartbeat
	GatewayHeartbeat
	Empty
	Request
	PutRequest
	PutResponse
	DeleteRequest
	DeleteResponse
	GetRequest
	GetResponse
	RangeGetRequest
	RangeGetResponse
	Response
	KeyValue
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// ////////////////////////////////////////////////
// 1. master received request to balance the data
type BalanceRequest struct {
	DataCenter string `protobuf:"bytes,1,opt,name=data_center,json=dataCenter" json:"data_center,omitempty"`
	StoreGroup string `protobuf:"bytes,2,opt,name=store_group,json=storeGroup" json:"store_group,omitempty"`
	StoreCount uint32 `protobuf:"varint,3,opt,name=store_count,json=storeCount" json:"store_count,omitempty"`
}

func (m *BalanceRequest) Reset()                    { *m = BalanceRequest{} }
func (m *BalanceRequest) String() string            { return proto.CompactTextString(m) }
func (*BalanceRequest) ProtoMessage()               {}
func (*BalanceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *BalanceRequest) GetDataCenter() string {
	if m != nil {
		return m.DataCenter
	}
	return ""
}

func (m *BalanceRequest) GetStoreGroup() string {
	if m != nil {
		return m.StoreGroup
	}
	return ""
}

func (m *BalanceRequest) GetStoreCount() uint32 {
	if m != nil {
		return m.StoreCount
	}
	return 0
}

type Topology struct {
	Rings []*Ring `protobuf:"bytes,1,rep,name=rings" json:"rings,omitempty"`
}

func (m *Topology) Reset()                    { *m = Topology{} }
func (m *Topology) String() string            { return proto.CompactTextString(m) }
func (*Topology) ProtoMessage()               {}
func (*Topology) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Topology) GetRings() []*Ring {
	if m != nil {
		return m.Rings
	}
	return nil
}

type Ring struct {
	DataCenter string           `protobuf:"bytes,1,opt,name=data_center,json=dataCenter" json:"data_center,omitempty"`
	StoreGroup string           `protobuf:"bytes,2,opt,name=store_group,json=storeGroup" json:"store_group,omitempty"`
	Stores     []*StoreResource `protobuf:"bytes,3,rep,name=stores" json:"stores,omitempty"`
	Proxies    []*Location      `protobuf:"bytes,4,rep,name=proxies" json:"proxies,omitempty"`
}

func (m *Ring) Reset()                    { *m = Ring{} }
func (m *Ring) String() string            { return proto.CompactTextString(m) }
func (*Ring) ProtoMessage()               {}
func (*Ring) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Ring) GetDataCenter() string {
	if m != nil {
		return m.DataCenter
	}
	return ""
}

func (m *Ring) GetStoreGroup() string {
	if m != nil {
		return m.StoreGroup
	}
	return ""
}

func (m *Ring) GetStores() []*StoreResource {
	if m != nil {
		return m.Stores
	}
	return nil
}

func (m *Ring) GetProxies() []*Location {
	if m != nil {
		return m.Proxies
	}
	return nil
}

type StoreResource struct {
	Id       int32     `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Location *Location `protobuf:"bytes,2,opt,name=location" json:"location,omitempty"`
}

func (m *StoreResource) Reset()                    { *m = StoreResource{} }
func (m *StoreResource) String() string            { return proto.CompactTextString(m) }
func (*StoreResource) ProtoMessage()               {}
func (*StoreResource) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *StoreResource) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *StoreResource) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

type Location struct {
	Server string `protobuf:"bytes,1,opt,name=server" json:"server,omitempty"`
	Port   int32  `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
}

func (m *Location) Reset()                    { *m = Location{} }
func (m *Location) String() string            { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()               {}
func (*Location) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Location) GetServer() string {
	if m != nil {
		return m.Server
	}
	return ""
}

func (m *Location) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

// ////////////////////////////////////////////////
type StoreHeartbeat struct {
	Store *StoreResource `protobuf:"bytes,1,opt,name=store" json:"store,omitempty"`
}

func (m *StoreHeartbeat) Reset()                    { *m = StoreHeartbeat{} }
func (m *StoreHeartbeat) String() string            { return proto.CompactTextString(m) }
func (*StoreHeartbeat) ProtoMessage()               {}
func (*StoreHeartbeat) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *StoreHeartbeat) GetStore() *StoreResource {
	if m != nil {
		return m.Store
	}
	return nil
}

type GatewayHeartbeat struct {
	Location *Location `protobuf:"bytes,1,opt,name=location" json:"location,omitempty"`
}

func (m *GatewayHeartbeat) Reset()                    { *m = GatewayHeartbeat{} }
func (m *GatewayHeartbeat) String() string            { return proto.CompactTextString(m) }
func (*GatewayHeartbeat) ProtoMessage()               {}
func (*GatewayHeartbeat) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *GatewayHeartbeat) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

// ////////////////////////////////////////////////
type Request struct {
	Put      *PutRequest      `protobuf:"bytes,1,opt,name=put" json:"put,omitempty"`
	Get      *GetRequest      `protobuf:"bytes,2,opt,name=get" json:"get,omitempty"`
	RangeGet *RangeGetRequest `protobuf:"bytes,3,opt,name=range_get,json=rangeGet" json:"range_get,omitempty"`
	Delete   *DeleteRequest   `protobuf:"bytes,4,opt,name=delete" json:"delete,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Request) GetPut() *PutRequest {
	if m != nil {
		return m.Put
	}
	return nil
}

func (m *Request) GetGet() *GetRequest {
	if m != nil {
		return m.Get
	}
	return nil
}

func (m *Request) GetRangeGet() *RangeGetRequest {
	if m != nil {
		return m.RangeGet
	}
	return nil
}

func (m *Request) GetDelete() *DeleteRequest {
	if m != nil {
		return m.Delete
	}
	return nil
}

type PutRequest struct {
	KeyValue    *KeyValue `protobuf:"bytes,1,opt,name=key_value,json=keyValue" json:"key_value,omitempty"`
	TimestampNs int64     `protobuf:"varint,2,opt,name=timestamp_ns,json=timestampNs" json:"timestamp_ns,omitempty"`
	TtlMs       uint32    `protobuf:"varint,3,opt,name=ttl_ms,json=ttlMs" json:"ttl_ms,omitempty"`
}

func (m *PutRequest) Reset()                    { *m = PutRequest{} }
func (m *PutRequest) String() string            { return proto.CompactTextString(m) }
func (*PutRequest) ProtoMessage()               {}
func (*PutRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *PutRequest) GetKeyValue() *KeyValue {
	if m != nil {
		return m.KeyValue
	}
	return nil
}

func (m *PutRequest) GetTimestampNs() int64 {
	if m != nil {
		return m.TimestampNs
	}
	return 0
}

func (m *PutRequest) GetTtlMs() uint32 {
	if m != nil {
		return m.TtlMs
	}
	return 0
}

type PutResponse struct {
	Ok     bool   `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
	Status string `protobuf:"bytes,2,opt,name=status" json:"status,omitempty"`
}

func (m *PutResponse) Reset()                    { *m = PutResponse{} }
func (m *PutResponse) String() string            { return proto.CompactTextString(m) }
func (*PutResponse) ProtoMessage()               {}
func (*PutResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *PutResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *PutResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type DeleteRequest struct {
	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (m *DeleteRequest) Reset()                    { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()               {}
func (*DeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *DeleteRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type DeleteResponse struct {
	Ok     bool   `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
	Status string `protobuf:"bytes,2,opt,name=status" json:"status,omitempty"`
}

func (m *DeleteResponse) Reset()                    { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()               {}
func (*DeleteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *DeleteResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *DeleteResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type GetRequest struct {
	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (m *GetRequest) Reset()                    { *m = GetRequest{} }
func (m *GetRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()               {}
func (*GetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *GetRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type GetResponse struct {
	Ok       bool      `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
	KeyValue *KeyValue `protobuf:"bytes,2,opt,name=key_value,json=keyValue" json:"key_value,omitempty"`
}

func (m *GetResponse) Reset()                    { *m = GetResponse{} }
func (m *GetResponse) String() string            { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()               {}
func (*GetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *GetResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *GetResponse) GetKeyValue() *KeyValue {
	if m != nil {
		return m.KeyValue
	}
	return nil
}

type RangeGetRequest struct {
	Prefix   []byte `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	StartKey []byte `protobuf:"bytes,2,opt,name=start_key,json=startKey,proto3" json:"start_key,omitempty"`
	Limit    uint32 `protobuf:"varint,3,opt,name=limit" json:"limit,omitempty"`
}

func (m *RangeGetRequest) Reset()                    { *m = RangeGetRequest{} }
func (m *RangeGetRequest) String() string            { return proto.CompactTextString(m) }
func (*RangeGetRequest) ProtoMessage()               {}
func (*RangeGetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *RangeGetRequest) GetPrefix() []byte {
	if m != nil {
		return m.Prefix
	}
	return nil
}

func (m *RangeGetRequest) GetStartKey() []byte {
	if m != nil {
		return m.StartKey
	}
	return nil
}

func (m *RangeGetRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type RangeGetResponse struct {
	KeyValues []*KeyValue `protobuf:"bytes,1,rep,name=key_values,json=keyValues" json:"key_values,omitempty"`
}

func (m *RangeGetResponse) Reset()                    { *m = RangeGetResponse{} }
func (m *RangeGetResponse) String() string            { return proto.CompactTextString(m) }
func (*RangeGetResponse) ProtoMessage()               {}
func (*RangeGetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *RangeGetResponse) GetKeyValues() []*KeyValue {
	if m != nil {
		return m.KeyValues
	}
	return nil
}

type Response struct {
	Put      *PutResponse      `protobuf:"bytes,1,opt,name=put" json:"put,omitempty"`
	Get      *GetResponse      `protobuf:"bytes,2,opt,name=get" json:"get,omitempty"`
	RangeGet *RangeGetResponse `protobuf:"bytes,3,opt,name=range_get,json=rangeGet" json:"range_get,omitempty"`
	Delete   *DeleteResponse   `protobuf:"bytes,4,opt,name=delete" json:"delete,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *Response) GetPut() *PutResponse {
	if m != nil {
		return m.Put
	}
	return nil
}

func (m *Response) GetGet() *GetResponse {
	if m != nil {
		return m.Get
	}
	return nil
}

func (m *Response) GetRangeGet() *RangeGetResponse {
	if m != nil {
		return m.RangeGet
	}
	return nil
}

func (m *Response) GetDelete() *DeleteResponse {
	if m != nil {
		return m.Delete
	}
	return nil
}

type KeyValue struct {
	Key   []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *KeyValue) Reset()                    { *m = KeyValue{} }
func (m *KeyValue) String() string            { return proto.CompactTextString(m) }
func (*KeyValue) ProtoMessage()               {}
func (*KeyValue) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *KeyValue) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *KeyValue) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*BalanceRequest)(nil), "pb.BalanceRequest")
	proto.RegisterType((*Topology)(nil), "pb.Topology")
	proto.RegisterType((*Ring)(nil), "pb.Ring")
	proto.RegisterType((*StoreResource)(nil), "pb.StoreResource")
	proto.RegisterType((*Location)(nil), "pb.Location")
	proto.RegisterType((*StoreHeartbeat)(nil), "pb.StoreHeartbeat")
	proto.RegisterType((*GatewayHeartbeat)(nil), "pb.GatewayHeartbeat")
	proto.RegisterType((*Empty)(nil), "pb.Empty")
	proto.RegisterType((*Request)(nil), "pb.Request")
	proto.RegisterType((*PutRequest)(nil), "pb.PutRequest")
	proto.RegisterType((*PutResponse)(nil), "pb.PutResponse")
	proto.RegisterType((*DeleteRequest)(nil), "pb.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "pb.DeleteResponse")
	proto.RegisterType((*GetRequest)(nil), "pb.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "pb.GetResponse")
	proto.RegisterType((*RangeGetRequest)(nil), "pb.RangeGetRequest")
	proto.RegisterType((*RangeGetResponse)(nil), "pb.RangeGetResponse")
	proto.RegisterType((*Response)(nil), "pb.Response")
	proto.RegisterType((*KeyValue)(nil), "pb.KeyValue")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for VastoMaster service

type VastoMasterClient interface {
	RegisterStore(ctx context.Context, opts ...grpc.CallOption) (VastoMaster_RegisterStoreClient, error)
	RegisterGateway(ctx context.Context, opts ...grpc.CallOption) (VastoMaster_RegisterGatewayClient, error)
}

type vastoMasterClient struct {
	cc *grpc.ClientConn
}

func NewVastoMasterClient(cc *grpc.ClientConn) VastoMasterClient {
	return &vastoMasterClient{cc}
}

func (c *vastoMasterClient) RegisterStore(ctx context.Context, opts ...grpc.CallOption) (VastoMaster_RegisterStoreClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_VastoMaster_serviceDesc.Streams[0], c.cc, "/pb.VastoMaster/RegisterStore", opts...)
	if err != nil {
		return nil, err
	}
	x := &vastoMasterRegisterStoreClient{stream}
	return x, nil
}

type VastoMaster_RegisterStoreClient interface {
	Send(*StoreHeartbeat) error
	Recv() (*Ring, error)
	grpc.ClientStream
}

type vastoMasterRegisterStoreClient struct {
	grpc.ClientStream
}

func (x *vastoMasterRegisterStoreClient) Send(m *StoreHeartbeat) error {
	return x.ClientStream.SendMsg(m)
}

func (x *vastoMasterRegisterStoreClient) Recv() (*Ring, error) {
	m := new(Ring)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *vastoMasterClient) RegisterGateway(ctx context.Context, opts ...grpc.CallOption) (VastoMaster_RegisterGatewayClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_VastoMaster_serviceDesc.Streams[1], c.cc, "/pb.VastoMaster/RegisterGateway", opts...)
	if err != nil {
		return nil, err
	}
	x := &vastoMasterRegisterGatewayClient{stream}
	return x, nil
}

type VastoMaster_RegisterGatewayClient interface {
	Send(*GatewayHeartbeat) error
	Recv() (*Topology, error)
	grpc.ClientStream
}

type vastoMasterRegisterGatewayClient struct {
	grpc.ClientStream
}

func (x *vastoMasterRegisterGatewayClient) Send(m *GatewayHeartbeat) error {
	return x.ClientStream.SendMsg(m)
}

func (x *vastoMasterRegisterGatewayClient) Recv() (*Topology, error) {
	m := new(Topology)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for VastoMaster service

type VastoMasterServer interface {
	RegisterStore(VastoMaster_RegisterStoreServer) error
	RegisterGateway(VastoMaster_RegisterGatewayServer) error
}

func RegisterVastoMasterServer(s *grpc.Server, srv VastoMasterServer) {
	s.RegisterService(&_VastoMaster_serviceDesc, srv)
}

func _VastoMaster_RegisterStore_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(VastoMasterServer).RegisterStore(&vastoMasterRegisterStoreServer{stream})
}

type VastoMaster_RegisterStoreServer interface {
	Send(*Ring) error
	Recv() (*StoreHeartbeat, error)
	grpc.ServerStream
}

type vastoMasterRegisterStoreServer struct {
	grpc.ServerStream
}

func (x *vastoMasterRegisterStoreServer) Send(m *Ring) error {
	return x.ServerStream.SendMsg(m)
}

func (x *vastoMasterRegisterStoreServer) Recv() (*StoreHeartbeat, error) {
	m := new(StoreHeartbeat)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _VastoMaster_RegisterGateway_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(VastoMasterServer).RegisterGateway(&vastoMasterRegisterGatewayServer{stream})
}

type VastoMaster_RegisterGatewayServer interface {
	Send(*Topology) error
	Recv() (*GatewayHeartbeat, error)
	grpc.ServerStream
}

type vastoMasterRegisterGatewayServer struct {
	grpc.ServerStream
}

func (x *vastoMasterRegisterGatewayServer) Send(m *Topology) error {
	return x.ServerStream.SendMsg(m)
}

func (x *vastoMasterRegisterGatewayServer) Recv() (*GatewayHeartbeat, error) {
	m := new(GatewayHeartbeat)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _VastoMaster_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.VastoMaster",
	HandlerType: (*VastoMasterServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RegisterStore",
			Handler:       _VastoMaster_RegisterStore_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "RegisterGateway",
			Handler:       _VastoMaster_RegisterGateway_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "vasto.proto",
}

// Client API for VastoStore service

type VastoStoreClient interface {
	Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error)
}

type vastoStoreClient struct {
	cc *grpc.ClientConn
}

func NewVastoStoreClient(cc *grpc.ClientConn) VastoStoreClient {
	return &vastoStoreClient{cc}
}

func (c *vastoStoreClient) Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error) {
	out := new(PutResponse)
	err := grpc.Invoke(ctx, "/pb.VastoStore/Put", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for VastoStore service

type VastoStoreServer interface {
	Put(context.Context, *PutRequest) (*PutResponse, error)
}

func RegisterVastoStoreServer(s *grpc.Server, srv VastoStoreServer) {
	s.RegisterService(&_VastoStore_serviceDesc, srv)
}

func _VastoStore_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VastoStoreServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.VastoStore/Put",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VastoStoreServer).Put(ctx, req.(*PutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _VastoStore_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.VastoStore",
	HandlerType: (*VastoStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Put",
			Handler:    _VastoStore_Put_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vasto.proto",
}

func init() { proto.RegisterFile("vasto.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 748 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x55, 0xdf, 0x6b, 0x1b, 0x47,
	0x10, 0xf6, 0xe9, 0x24, 0xf9, 0x34, 0xfa, 0xe5, 0x6e, 0xdd, 0x22, 0x5c, 0x70, 0xa5, 0x7d, 0x68,
	0x65, 0x17, 0x8c, 0x2b, 0x53, 0xd3, 0xd2, 0x42, 0xa1, 0x6e, 0xb0, 0x83, 0xe3, 0x60, 0x36, 0xc1,
	0x4f, 0x01, 0xb1, 0x92, 0x36, 0xc7, 0xa1, 0xd3, 0xed, 0xf9, 0x76, 0xcf, 0xb1, 0x9e, 0xf2, 0x87,
	0xe4, 0x3f, 0xc8, 0x4b, 0xfe, 0xc5, 0xb0, 0x73, 0x7b, 0x77, 0x92, 0xec, 0x18, 0x02, 0x79, 0xbb,
	0xfd, 0xe6, 0x9b, 0xd9, 0x6f, 0x66, 0x3f, 0xe6, 0xa0, 0x79, 0xc7, 0x95, 0x96, 0x47, 0x71, 0x22,
	0xb5, 0x24, 0x95, 0x78, 0x42, 0x15, 0x74, 0xfe, 0xe3, 0x21, 0x8f, 0xa6, 0x82, 0x89, 0xdb, 0x54,
	0x28, 0x4d, 0x7e, 0x86, 0xe6, 0x8c, 0x6b, 0x3e, 0x9e, 0x8a, 0x48, 0x8b, 0xa4, 0xe7, 0xf4, 0x9d,
	0x61, 0x83, 0x81, 0x81, 0xce, 0x10, 0x31, 0x04, 0xa5, 0x65, 0x22, 0xc6, 0x7e, 0x22, 0xd3, 0xb8,
	0x57, 0xc9, 0x08, 0x08, 0x9d, 0x1b, 0xa4, 0x24, 0x4c, 0x65, 0x1a, 0xe9, 0x9e, 0xdb, 0x77, 0x86,
	0x6d, 0x4b, 0x38, 0x33, 0x08, 0x3d, 0x04, 0xef, 0xb5, 0x8c, 0x65, 0x28, 0xfd, 0x25, 0xd9, 0x87,
	0x5a, 0x12, 0x44, 0xbe, 0xea, 0x39, 0x7d, 0x77, 0xd8, 0x1c, 0x79, 0x47, 0xf1, 0xe4, 0x88, 0x05,
	0x91, 0xcf, 0x32, 0x98, 0x7e, 0x70, 0xa0, 0x6a, 0xce, 0xdf, 0x40, 0xd7, 0x01, 0xd4, 0xf1, 0xa4,
	0x7a, 0x2e, 0xde, 0xf5, 0x9d, 0xb9, 0xeb, 0x95, 0x41, 0x98, 0x50, 0x32, 0x4d, 0xa6, 0x82, 0x59,
	0x02, 0xf9, 0x05, 0xb6, 0xe3, 0x44, 0xde, 0x07, 0x42, 0xf5, 0xaa, 0xc8, 0x6d, 0x19, 0xee, 0x0b,
	0x39, 0xe5, 0x3a, 0x90, 0x11, 0xcb, 0x83, 0xf4, 0x39, 0xb4, 0xd7, 0x0a, 0x90, 0x0e, 0x54, 0x82,
	0x19, 0x8a, 0xab, 0xb1, 0x4a, 0x30, 0x23, 0x43, 0xf0, 0x42, 0x9b, 0x85, 0x8a, 0x36, 0x2b, 0x15,
	0x51, 0x7a, 0x0a, 0x5e, 0x8e, 0x92, 0x1f, 0xa1, 0xae, 0x44, 0x72, 0x57, 0xb4, 0x69, 0x4f, 0x84,
	0x40, 0x35, 0x96, 0x89, 0xc6, 0x4a, 0x35, 0x86, 0xdf, 0xf4, 0x2f, 0xe8, 0xa0, 0x84, 0x0b, 0xc1,
	0x13, 0x3d, 0x11, 0x5c, 0x93, 0x5f, 0xa1, 0x86, 0x6d, 0x60, 0xf2, 0xa3, 0x6d, 0x66, 0x71, 0xfa,
	0x0f, 0xec, 0x9c, 0x73, 0x2d, 0xde, 0xf1, 0x65, 0x99, 0xbc, 0x2a, 0xd8, 0x79, 0x52, 0xf0, 0x36,
	0xd4, 0x9e, 0x2d, 0x62, 0xbd, 0xa4, 0x1f, 0x1d, 0xd8, 0xce, 0xdd, 0xd3, 0x07, 0x37, 0x4e, 0xb5,
	0xcd, 0xec, 0x98, 0xcc, 0xeb, 0x54, 0xdb, 0x20, 0x33, 0x21, 0xc3, 0xf0, 0x85, 0xb6, 0xc3, 0x40,
	0xc6, 0xb9, 0x28, 0x19, 0xbe, 0xd0, 0xe4, 0x18, 0x1a, 0x09, 0x8f, 0x7c, 0x31, 0x36, 0x3c, 0x17,
	0x79, 0xdf, 0xa3, 0x2d, 0x0c, 0xb8, 0x42, 0xf6, 0x12, 0x0b, 0x98, 0x97, 0x9d, 0x89, 0x50, 0x68,
	0xd1, 0xab, 0x96, 0x2d, 0xff, 0x8f, 0x48, 0x4e, 0xb6, 0x04, 0x7a, 0x0b, 0x50, 0x2a, 0x22, 0x07,
	0xd0, 0x98, 0x8b, 0xe5, 0xf8, 0x8e, 0x87, 0xa9, 0x58, 0x6d, 0xf7, 0x52, 0x2c, 0x6f, 0x0c, 0xc6,
	0xbc, 0xb9, 0xfd, 0x22, 0x03, 0x68, 0xe9, 0x60, 0x21, 0x94, 0xe6, 0x8b, 0x78, 0x1c, 0x29, 0x6c,
	0xc0, 0x65, 0xcd, 0x02, 0x7b, 0xa9, 0xc8, 0x0f, 0x50, 0xd7, 0x3a, 0x1c, 0x2f, 0x94, 0xf5, 0x7c,
	0x4d, 0xeb, 0xf0, 0x4a, 0xd1, 0x3f, 0xa0, 0x89, 0x57, 0xaa, 0x58, 0x46, 0x0a, 0x2d, 0x22, 0xe7,
	0x78, 0x99, 0xc7, 0x2a, 0x72, 0x8e, 0x8f, 0xad, 0xb9, 0x4e, 0x95, 0xb5, 0xac, 0x3d, 0xd1, 0x01,
	0xb4, 0xd7, 0x5a, 0x20, 0x3b, 0xe0, 0xce, 0xc5, 0x12, 0x33, 0x5b, 0xcc, 0x7c, 0xd2, 0x3f, 0xa1,
	0x93, 0x53, 0xbe, 0xb2, 0xf8, 0x3e, 0x40, 0x39, 0xc9, 0x47, 0x2a, 0x5f, 0x40, 0x13, 0xe3, 0x5f,
	0x28, 0xbb, 0x36, 0xb7, 0xca, 0x53, 0x73, 0xa3, 0x6f, 0xa0, 0xbb, 0xf1, 0x70, 0x46, 0x54, 0x9c,
	0x88, 0xb7, 0xc1, 0xbd, 0xbd, 0xd1, 0x9e, 0xc8, 0x4f, 0xd0, 0x50, 0x9a, 0x27, 0x7a, 0x6c, 0xc4,
	0x54, 0x30, 0xe4, 0x21, 0x70, 0x29, 0x96, 0x64, 0x17, 0x6a, 0x61, 0xb0, 0x08, 0xf2, 0x7d, 0x92,
	0x1d, 0xe8, 0xbf, 0xb0, 0x53, 0x56, 0xb7, 0x62, 0x7f, 0x03, 0x28, 0xc4, 0xe5, 0x7b, 0x65, 0x5d,
	0x5d, 0x23, 0x57, 0xa7, 0xe8, 0x27, 0x07, 0xbc, 0x22, 0x73, 0xb0, 0xea, 0xde, 0x6e, 0xe1, 0xde,
	0x2c, 0x9a, 0xd9, 0x77, 0xb0, 0x6a, 0xdf, 0x6e, 0x61, 0xdf, 0x9c, 0x62, 0xfc, 0xfb, 0xfb, 0x43,
	0xff, 0xee, 0xae, 0xfb, 0xd7, 0xb2, 0x4b, 0x03, 0x1f, 0x6e, 0x18, 0x98, 0xac, 0x1a, 0xd8, 0xb2,
	0x73, 0x07, 0x8f, 0xc0, 0xcb, 0x1b, 0x79, 0xf8, 0x70, 0x66, 0x4c, 0xe5, 0xab, 0xb4, 0x58, 0x76,
	0x18, 0xbd, 0x87, 0xe6, 0x8d, 0xd9, 0xfc, 0x57, 0x5c, 0x99, 0x55, 0x79, 0x02, 0x6d, 0x26, 0xfc,
	0xc0, 0x7c, 0xe3, 0x62, 0x20, 0xa4, 0xd8, 0x11, 0xc5, 0x26, 0xd8, 0x2b, 0x56, 0x31, 0xdd, 0x1a,
	0x3a, 0xc7, 0x0e, 0xf9, 0x1b, 0xba, 0x79, 0x92, 0xdd, 0x1a, 0x04, 0xdb, 0xda, 0x5c, 0x21, 0x7b,
	0x38, 0xeb, 0x7c, 0xc1, 0x67, 0xc9, 0xa3, 0x53, 0x00, 0x14, 0x90, 0x5d, 0x37, 0x04, 0xf7, 0x3a,
	0xd5, 0x64, 0x63, 0x3f, 0xec, 0x6d, 0x4e, 0x9c, 0x6e, 0x4d, 0xea, 0xf8, 0xab, 0x3a, 0xf9, 0x1c,
	0x00, 0x00, 0xff, 0xff, 0xc3, 0xe9, 0x32, 0x62, 0xb9, 0x06, 0x00, 0x00,
}
